with open("/workspaces/media-on-gas/dashboard/src/App.jsx", "r") as f:
    c = f.read()

# ============ FIX 1: REPORTING TAB - Per-Objective Insights (line 342 area) ============
# Replace the platBreakdown forEach sections with confidence-aware versions

# App Store Clicks insight
old_app = 'if(objName==="App Store Clicks"){p.push("App store click campaigns invested "+fR(totalSpend)+" to deliver "+fmt(totalResults)+" clicks to the app store at "+fR(totalCostPer)+" blended Cost Per Click with a "+blendedCtr.toFixed(2)+"% Click Through Rate.");platBreakdown.forEach(function(pb){if(pb.result>0){p.push(pb.platform+" delivered "+fmt(pb.result)+" app store clicks at "+fR(pb.cost)+" Cost Per Click with "+pb.ctr.toFixed(2)+"% Click Through Rate"+(pb.cost<=totalCostPer?" performing at or below the blended cost, confirming efficient audience targeting on this platform.":"."));}});if(platBreakdown.length>1){var cheapest=platBreakdown.reduce(function(a,b){return a.cost<b.cost&&a.cost>0?a:b;});p.push("Strategy: "+cheapest.platform+" delivers the lowest Cost Per Click at "+fR(cheapest.cost)+". Prioritising budget allocation toward "+cheapest.platform+" while maintaining presence on other platforms would maximise app store traffic volume within the current investment level.");}}'

new_app = 'if(objName==="App Store Clicks"){p.push("App store click campaigns invested "+fR(totalSpend)+" to deliver "+fmt(totalResults)+" clicks to the app store at "+fR(totalCostPer)+" blended Cost Per Click with a "+blendedCtr.toFixed(2)+"% Click Through Rate.");var scalePlats=platBreakdown.filter(function(pb){return pb.result>0&&pb.spend>=totalSpend*0.05&&pb.imps>=5000;});var smallPlats=platBreakdown.filter(function(pb){return pb.result>0&&(pb.spend<totalSpend*0.05||pb.imps<5000);});scalePlats.forEach(function(pb){var shareR=totalResults>0?((pb.result/totalResults)*100).toFixed(0):"0";var shareS=totalSpend>0?((pb.spend/totalSpend)*100).toFixed(0):"0";var effR=parseFloat(shareS)>0?(parseFloat(shareR)/parseFloat(shareS)).toFixed(1):"0";p.push(pb.platform+" delivered "+fmt(pb.result)+" app store clicks ("+shareR+"% of total) from "+shareS+"% of budget at "+fR(pb.cost)+" Cost Per Click with "+pb.ctr.toFixed(2)+"% CTR."+(parseFloat(effR)>=1.2?" This platform delivers "+effR+"x more results per rand than its budget share, confirming strong efficiency at scale.":parseFloat(effR)<0.7?" This platform consumes a disproportionate budget share relative to its result contribution.":""));});if(smallPlats.length>0){smallPlats.forEach(function(pb){p.push(pb.platform+" shows "+fmt(pb.result)+" app store clicks at "+fR(pb.cost)+" CPC from "+fR(pb.spend)+" spend. Volume is currently too low to draw reliable performance conclusions.");});}if(scalePlats.length>1){var cheapest=scalePlats.reduce(function(a,b){return a.cost<b.cost&&a.cost>0?a:b;});p.push("Strategy: Among platforms with proven scale, "+cheapest.platform+" delivers the most efficient Cost Per Click at "+fR(cheapest.cost)+". Increasing allocation toward "+cheapest.platform+" would maximise app store traffic within the current investment.");}}'

c = c.replace(old_app, new_app)
print("Fix 1a: App Store Clicks insight with confidence")

# Landing Page Clicks insight
old_lp = 'if(objName==="Landing Page Clicks"){p.push("Landing page campaigns invested "+fR(totalSpend)+" generating "+fmt(totalResults)+" qualified site visits at "+fR(totalCostPer)+" blended cost per visit with "+blendedCtr.toFixed(2)+"% Click Through Rate.");platBreakdown.forEach(function(pb){if(pb.result>0){p.push(pb.platform+" drove "+fmt(pb.result)+" landing page visits at "+fR(pb.cost)+" cost per visit with "+pb.ctr.toFixed(2)+"% Click Through Rate"+(pb.ctr>blendedCtr?" outperforming the blended Click Through Rate, indicating strong creative-audience alignment on this platform.":"."));}});if(platBreakdown.length>1){var highCtr=platBreakdown.reduce(function(a,b){return a.ctr>b.ctr?a:b;});p.push("Strategy: "+highCtr.platform+" leads with "+highCtr.ctr.toFixed(2)+"% Click Through Rate, suggesting the highest creative resonance. Testing additional creative variants on "+highCtr.platform+" could unlock further volume at efficient cost levels.");}}'

new_lp = 'if(objName==="Landing Page Clicks"){p.push("Landing page campaigns invested "+fR(totalSpend)+" generating "+fmt(totalResults)+" qualified site visits at "+fR(totalCostPer)+" blended cost per visit with "+blendedCtr.toFixed(2)+"% Click Through Rate.");var lpScale=platBreakdown.filter(function(pb){return pb.result>0&&pb.spend>=totalSpend*0.05&&pb.imps>=5000;});var lpSmall=platBreakdown.filter(function(pb){return pb.result>0&&(pb.spend<totalSpend*0.05||pb.imps<5000);});lpScale.forEach(function(pb){var shareR=totalResults>0?((pb.result/totalResults)*100).toFixed(0):"0";var shareS=totalSpend>0?((pb.spend/totalSpend)*100).toFixed(0):"0";p.push(pb.platform+" drove "+fmt(pb.result)+" landing page visits ("+shareR+"% of total) at "+fR(pb.cost)+" cost per visit with "+pb.ctr.toFixed(2)+"% CTR from "+shareS+"% of objective budget."+(pb.ctr>blendedCtr*1.2?" CTR outperforms the blended average by "+((pb.ctr/blendedCtr-1)*100).toFixed(0)+"%, confirming strong creative-audience alignment.":""));});if(lpSmall.length>0){lpSmall.forEach(function(pb){p.push(pb.platform+" contributed "+fmt(pb.result)+" visits at "+fR(pb.cost)+" from "+fR(pb.spend)+" spend. Insufficient volume to confirm sustained performance.");});}if(lpScale.length>1){var highCtr=lpScale.reduce(function(a,b){return a.ctr>b.ctr?a:b;});p.push("Strategy: Among platforms with proven delivery, "+highCtr.platform+" leads with "+highCtr.ctr.toFixed(2)+"% CTR across "+fmt(highCtr.imps)+" impressions, confirming the highest creative resonance at scale.");}}'

c = c.replace(old_lp, new_lp)
print("Fix 1b: Landing Page insight with confidence")

# Leads insight
old_leads = 'if(objName==="Leads"){var convRate=totalClicks>0?(totalResults/totalClicks*100):0;p.push("Lead generation campaigns invested "+fR(totalSpend)+" producing "+fmt(totalResults)+" qualified leads at "+fR(totalCostPer)+" Cost Per Lead with a "+convRate.toFixed(1)+"% click-to-lead conversion rate.");platBreakdown.forEach(function(pb){if(pb.result>0){var pbConv=pb.result>0&&pb.spend>0?pb.result:0;p.push(pb.platform+" generated "+fmt(pb.result)+" leads at "+fR(pb.cost)+" Cost Per Lead"+(pb.cost<totalCostPer?" outperforming the blended Cost Per Lead, representing the most efficient lead source in the campaign.":"."));}});if(totalResults>0){p.push("Strategy: Each lead represents a qualified prospect who has actively shared contact information. Nurturing these "+fmt(totalResults)+" leads through timely follow-up within 24-48 hours significantly increases conversion probability from lead to customer.");}}'

new_leads = 'if(objName==="Leads"){var convRate=totalClicks>0?(totalResults/totalClicks*100):0;p.push("Lead generation campaigns invested "+fR(totalSpend)+" producing "+fmt(totalResults)+" qualified leads at "+fR(totalCostPer)+" Cost Per Lead with a "+convRate.toFixed(1)+"% click-to-lead conversion rate.");var ldScale=platBreakdown.filter(function(pb){return pb.result>0&&pb.spend>=totalSpend*0.05;});var ldSmall=platBreakdown.filter(function(pb){return pb.result>0&&pb.spend<totalSpend*0.05;});ldScale.forEach(function(pb){var shareR=totalResults>0?((pb.result/totalResults)*100).toFixed(0):"0";var shareS=totalSpend>0?((pb.spend/totalSpend)*100).toFixed(0):"0";var effR=parseFloat(shareS)>0?(parseFloat(shareR)/parseFloat(shareS)).toFixed(1):"0";p.push(pb.platform+" generated "+fmt(pb.result)+" leads ("+shareR+"% of total) at "+fR(pb.cost)+" Cost Per Lead from "+shareS+"% of objective budget."+(parseFloat(effR)>=1.2?" Delivering "+effR+"x more leads per rand than its budget share.":parseFloat(effR)<0.7?" This platform is underdelivering relative to its budget allocation.":""));});if(ldSmall.length>0){ldSmall.forEach(function(pb){p.push(pb.platform+" produced "+fmt(pb.result)+" leads at "+fR(pb.cost)+" from "+fR(pb.spend)+" spend. Low volume means this is an early indicator, not a confirmed trend.");});}if(totalResults>0){p.push("Strategy: Each lead represents a qualified prospect who has actively shared contact information. Timely follow-up within 24-48 hours significantly increases conversion probability.");}}'

c = c.replace(old_leads, new_leads)
print("Fix 1c: Leads insight with confidence")

# Followers & Likes insight
old_follows = """if(objName==="Followers & Likes"){p.push("Community growth campaigns invested "+fR(totalSpend)+" acquiring "+fmt(totalResults)+" new followers and likes at "+fR(totalCostPer)+" blended cost per acquisition.");platBreakdown.forEach(function(pb){if(pb.result>0){p.push(pb.platform+" contributed "+fmt(pb.result)+" new community members at "+fR(pb.cost)+" cost per acquisition"+(pb.cost<totalCostPer?" delivering the most cost-efficient community growth in the campaign.":"."));}});if(totalResults>0){p.push("Strategy: Community growth is a compounding investment. The "+fmt(totalResults)+" new members acquired will increase organic content distribution across future campaigns, progressively reducing paid media dependency and strengthening the brand\\'s owned audience reach.");}}"""

new_follows = """if(objName==="Followers & Likes"){p.push("Community growth campaigns invested "+fR(totalSpend)+" acquiring "+fmt(totalResults)+" new followers and likes at "+fR(totalCostPer)+" blended cost per acquisition.");var flScale=platBreakdown.filter(function(pb){return pb.result>=10&&pb.spend>=totalSpend*0.05;});var flSmall=platBreakdown.filter(function(pb){return pb.result>0&&(pb.result<10||pb.spend<totalSpend*0.05);});flScale.forEach(function(pb){var shareR=totalResults>0?((pb.result/totalResults)*100).toFixed(0):"0";var shareS=totalSpend>0?((pb.spend/totalSpend)*100).toFixed(0):"0";p.push(pb.platform+" contributed "+fmt(pb.result)+" new community members ("+shareR+"% of total) at "+fR(pb.cost)+" cost per acquisition from "+shareS+"% of community budget."+(pb.cost<totalCostPer?" This platform delivers community growth below the blended average, confirming efficient audience acquisition.":""));});if(flSmall.length>0){flSmall.forEach(function(pb){p.push(pb.platform+" added "+fmt(pb.result)+" members at "+fR(pb.cost)+" from "+fR(pb.spend)+" spend. Volume is early-stage and not yet statistically significant.");});}if(totalResults>0){p.push("Strategy: Community growth is a compounding investment. The "+fmt(totalResults)+" new members acquired will increase organic content distribution, progressively reducing paid media dependency and strengthening the brand's owned audience reach.");}}"""

c = c.replace(old_follows, new_follows)
print("Fix 1d: Followers & Likes insight with confidence")

# ============ FIX 2: TARGETING TAB - Per-Objective Assessments (line 543 area) ============
old_targeting_insight = """p.push(objName+" targeting operates "+sorted6.length+" adsets across "+Object.keys(platGrp).join(", ")+" with "+fR(oSpend)+" total investment delivering "+fmt(oResults)+" results"+(oResults>0?" at "+fR(oCostPer)+" blended cost per result":"")+" and "+oCtr.toFixed(2)+"% Click Through Rate.");Object.keys(platGrp).sort(function(a,b){return (platOrd3[a]||9)-(platOrd3[b]||9);}).forEach(function(plat){var pg=platGrp[plat];var pgCtr=pg.imps>0?(pg.clicks/pg.imps*100):0;var pgCost=pg.results>0?pg.spend/pg.results:0;p.push(plat+" contributes "+fmt(pg.results)+" results from "+pg.rows.length+" adset"+(pg.rows.length>1?"s":"")+" at "+fR(pg.spend)+" spend"+(pg.results>0?" with "+fR(pgCost)+" cost per result":"")+" and "+pgCtr.toFixed(2)+"% CTR.");if(pg.rows.length>1){var pBest=pg.rows.reduce(function(a,r){return r.result>a.result?r:a;},{result:0});if(pBest.result>0){p.push("The strongest "+plat+" adset is "+pBest.adsetName+" delivering "+fmt(pBest.result)+" results"+(pBest.costPer>0?" at "+fR(pBest.costPer)+" cost per result":"")+".");}}});if(bestAd.result>0){p.push("Overall top performer across all platforms: "+bestAd.adsetName+" on "+bestAd.platform+" with "+fmt(bestAd.result)+" results"+(bestAd.costPer>0?" at "+fR(bestAd.costPer)+" cost per result":"")+" and "+bestAd.ctr.toFixed(2)+"% CTR. "+(bestAd.ctr>3?"This audience segment demonstrates exceptional creative resonance.":bestAd.ctr>1.5?"This targeting is performing within the upper engagement band.":"This adset is the primary results driver for this objective."));}var zeroSpend=sorted6.filter(function(r){return r.spend>200&&r.result===0;});if(zeroSpend.length>0){p.push(zeroSpend.length+" adset"+(zeroSpend.length>1?"s have":" has")+" invested budget without producing results. These segments are not converting under the current configuration.");}"""

new_targeting_insight = """p.push(objName+" targeting operates "+sorted6.length+" adsets across "+Object.keys(platGrp).join(", ")+" with "+fR(oSpend)+" total investment delivering "+fmt(oResults)+" results"+(oResults>0?" at "+fR(oCostPer)+" blended cost per result":"")+" and "+oCtr.toFixed(2)+"% Click Through Rate.");Object.keys(platGrp).sort(function(a,b){return (platOrd3[a]||9)-(platOrd3[b]||9);}).forEach(function(plat){var pg=platGrp[plat];var pgCtr=pg.imps>0?(pg.clicks/pg.imps*100):0;var pgCost=pg.results>0?pg.spend/pg.results:0;var pgShareR=oResults>0?((pg.results/oResults)*100).toFixed(0):"0";var pgShareS=oSpend>0?((pg.spend/oSpend)*100).toFixed(0):"0";var pgEff=parseFloat(pgShareS)>0?(parseFloat(pgShareR)/parseFloat(pgShareS)).toFixed(1):"0";var pgHasScale=pg.spend>=oSpend*0.05&&pg.imps>=5000&&pg.results>=3;p.push(plat+" contributes "+fmt(pg.results)+" results ("+pgShareR+"%) from "+pgShareS+"% of objective budget"+(pg.results>0?" at "+fR(pgCost)+" cost per result":"")+" and "+pgCtr.toFixed(2)+"% CTR.");if(pgHasScale&&parseFloat(pgEff)>=1.3){p.push(plat+" delivers "+pgEff+"x more results per rand than its budget share, confirmed across "+fmt(pg.imps)+" impressions.");}else if(pgHasScale&&parseFloat(pgEff)<0.7){p.push(plat+" is underdelivering at "+pgEff+"x efficiency ratio across "+fmt(pg.imps)+" impressions, consuming more budget than its result contribution warrants.");}else if(!pgHasScale&&pg.results>0){p.push(plat+" results are from limited volume ("+fR(pg.spend)+" spend, "+fmt(pg.imps)+" impressions). Insufficient data to confirm whether this efficiency is sustainable at scale.");}if(pgHasScale&&pg.rows.length>1){var pBest=pg.rows.reduce(function(a,r){return r.result>a.result?r:a;},{result:0});var pBestShare=pg.results>0?((pBest.result/pg.results)*100).toFixed(0):"0";if(pBest.result>0&&pBest.spend>=pg.spend*0.1){p.push("The strongest "+plat+" adset is "+pBest.adsetName+" delivering "+pBestShare+"% of "+plat+" results"+(pBest.costPer>0?" at "+fR(pBest.costPer)+" cost per result":"")+".");}}});if(bestAd.result>0&&bestAd.spend>=oSpend*0.05&&bestAd.impressions>=5000){p.push("Overall top performer with proven scale: "+bestAd.adsetName+" on "+bestAd.platform+" with "+fmt(bestAd.result)+" results"+(bestAd.costPer>0?" at "+fR(bestAd.costPer)+" cost per result":"")+" across "+fmt(bestAd.impressions)+" impressions.");}else if(bestAd.result>0){p.push("Highest result count is "+bestAd.adsetName+" on "+bestAd.platform+" with "+fmt(bestAd.result)+" results, though at "+fR(bestAd.spend)+" spend this requires further volume to confirm sustained efficiency.");}var zeroSpend=sorted6.filter(function(r){return r.spend>200&&r.result===0;});if(zeroSpend.length>0){var zeroTotal=zeroSpend.reduce(function(a,r){return a+r.spend;},0);p.push(zeroSpend.length+" adset"+(zeroSpend.length>1?"s have":" has")+" invested "+fR(zeroTotal)+" without producing results. This represents "+((zeroTotal/oSpend)*100).toFixed(1)+"% of objective budget with zero return.");}"""

c = c.replace(old_targeting_insight, new_targeting_insight)
print("Fix 2: Targeting per-objective insight with confidence")

with open("/workspaces/media-on-gas/dashboard/src/App.jsx", "w") as f:
    f.write(c)
print("All confidence fixes applied")
