with open("/workspaces/media-on-gas/dashboard/src/App.jsx", "r") as f:
    c = f.read()

# The Grand Total row in awareness table needs correct weighted calculations
# Replace grand total row in awareness
old_grand_awareness = '<tr style={{background:"rgba(255,107,0,0.15)"}}><td style={{padding:"12px",border:"1px solid #002a40"}}><span style={{fontSize:13,fontWeight:900,color:"#FFCB05"}}>GRAND TOTAL</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#FFCB05",fontFamily:fm,fontSize:15,fontWeight:900}}>{fR(computed.totalSpend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#FFCB05",fontFamily:fm,fontSize:15,fontWeight:900}}>{fmt(computed.totalImps)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#FFCB05",fontFamily:fm,fontSize:15,fontWeight:900}}>{fmt(computed.grand.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#FFCB05",fontFamily:fm,fontSize:15,fontWeight:900}}>{fR(computed.blendedCpm)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#FFCB05",fontFamily:fm,fontSize:15,fontWeight:900}}>{computed.grand.frequency>0?computed.grand.frequency.toFixed(2)+"x":"0"}</td></tr>'

new_grand_awareness = '<tr style={{background:"rgba(255,107,0,0.15)"}}><td style={{padding:"12px",border:"1px solid #002a40"}}><span style={{fontSize:13,fontWeight:900,color:"#FFCB05"}}>GRAND TOTAL</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#FFCB05",fontFamily:fm,fontSize:15,fontWeight:900}}>{fR(computed.totalSpend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#FFCB05",fontFamily:fm,fontSize:15,fontWeight:900}}>{fmt(computed.totalImps)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#FFCB05",fontFamily:fm,fontSize:15,fontWeight:900}}>{fmt(m.reach+t.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#FFCB05",fontFamily:fm,fontSize:15,fontWeight:900}}>{fR(computed.totalImps>0?(computed.totalSpend/computed.totalImps)*1000:0)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#FFCB05",fontFamily:fm,fontSize:15,fontWeight:900}}>{(m.reach+t.reach)>0?((m.impressions+t.impressions)/(m.reach+t.reach)).toFixed(2)+"x":"0"}</td></tr>'

c = c.replace(old_grand_awareness, new_grand_awareness)

# Fix Grand Total in engagement table - weighted CTR and CPC
old_grand_engage = '<tr style={{background:"rgba(255,107,0,0.12)"}}><td style={{padding:"12px",border:"1px solid "+P.rule}}><span style={{fontSize:13,fontWeight:900,color:P.ember}}>GRAND TOTAL</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{fR(computed.totalSpend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{fmt(computed.grand.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{fmt(computed.totalClicks)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{pc(computed.grand.ctr)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{fR(computed.grand.cpc)}</td></tr>'

new_grand_engage = '<tr style={{background:"rgba(255,107,0,0.12)"}}><td style={{padding:"12px",border:"1px solid "+P.rule}}><span style={{fontSize:13,fontWeight:900,color:P.ember}}>GRAND TOTAL</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{fR(computed.totalSpend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{fmt(m.reach+t.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{fmt(m.clicks+t.clicks)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{pc(computed.totalImps>0?((m.clicks+t.clicks)/computed.totalImps)*100:0)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{fR((m.clicks+t.clicks)>0?computed.totalSpend/(m.clicks+t.clicks):0)}</td></tr>'

c = c.replace(old_grand_engage, new_grand_engage)

with open("/workspaces/media-on-gas/dashboard/src/App.jsx", "w") as f:
    f.write(c)
print("Done - grand totals fixed with weighted calculations")
print("Grand awareness found:", new_grand_awareness[:30] in c)
print("Grand engage found:", new_grand_engage[:30] in c)
