with open("/workspaces/media-on-gas/dashboard/src/App.jsx", "r") as f:
    c = f.read()

# Fix awareness insight
old_awareness = '''The campaign has served <strong>{fmt(computed.totalImps)} impressions</strong> across Facebook ({fmt(computed.fb.impressions)}), Instagram ({fmt(computed.ig.impressions)}), and TikTok ({fmt(t.impressions)}) against <strong>{fR(computed.totalSpend)}</strong> total investment. Facebook delivers the richest audience data with {fmt(computed.fb.reach)} unique reach at {computed.fb.frequency>0?computed.fb.frequency.toFixed(2)+"x":"N/A"} frequency, whilst TikTok provides the most cost-efficient impressions at {fR(t.cpm)} CPM. The blended campaign CPM of <strong>{fR(computed.blendedCpm)}</strong> represents strong media value in the South African paid social market. {computed.fb.frequency>3?"Warning: Facebook frequency at "+computed.fb.frequency.toFixed(2)+"x is approaching the fatigue threshold \u2014 consider audience expansion or creative refresh.":""}'''

new_awareness = '''{(function(){var parts=[];parts.push("The selected campaigns have served "+fmt(computed.totalImps)+" total impressions against "+fR(computed.totalSpend)+" investment at "+fR(computed.blendedCpm)+" blended CPM.");if(computed.fb.impressions>0)parts.push("Facebook delivered "+fmt(computed.fb.impressions)+" impressions reaching "+fmt(computed.fb.reach)+" unique people at "+computed.fb.frequency.toFixed(2)+"x frequency and "+fR(computed.fb.cpm)+" CPM.");if(computed.ig.impressions>0)parts.push("Instagram contributed "+fmt(computed.ig.impressions)+" impressions reaching "+fmt(computed.ig.reach)+" unique people at "+fR(computed.ig.cpm)+" CPM.");if(t.impressions>0)parts.push("TikTok delivered "+fmt(t.impressions)+" impressions at "+fR(t.cpm)+" CPM, the most cost-efficient impression channel in the campaign.");if(computed.fb.frequency>3)parts.push("Warning: Facebook frequency at "+computed.fb.frequency.toFixed(2)+"x is approaching the fatigue threshold \u2014 consider audience expansion or creative refresh.");return parts.join(" ");})()}'''

c = c.replace(old_awareness, new_awareness)

# Fix engagement insight
old_engagement = '''Facebook has generated <strong>{fmt(computed.fb.clicks)} clicks</strong> at <strong>{fR(computed.fb.cpc)} CPC</strong> with {pc(computed.fb.ctr)} CTR, confirming strong creative-audience alignment on the platform. Instagram contributed {fmt(computed.ig.clicks)} clicks at {fR(computed.ig.cpc)} CPC with {pc(computed.ig.ctr)} CTR. The combined Meta engagement of <strong>{fmt(m.clicks)} clicks</strong> at {fR(m.cpc)} blended CPC represents efficient conversion of awareness into measurable intent signals. TikTok contributed {fmt(t.clicks)} clicks through its performance network, with engagement metrics carrying additional amplification value as TikTok\u2019s algorithm promotes content with strong interaction signals. {m.cpc<2?"Meta CPC below R2.00 is a positive efficiency signal \u2014 consider scaling budget on top-performing ad sets.":m.cpc>5?"Meta CPC above R5.00 warrants creative review and potential audience refresh.":""}'''

new_engagement = '''{(function(){var parts=[];if(computed.fb.clicks>0)parts.push("Facebook generated "+fmt(computed.fb.clicks)+" clicks at "+fR(computed.fb.cpc)+" CPC with "+pc(computed.fb.ctr)+" CTR, confirming strong creative-audience alignment.");if(computed.ig.clicks>0)parts.push("Instagram contributed "+fmt(computed.ig.clicks)+" clicks at "+fR(computed.ig.cpc)+" CPC with "+pc(computed.ig.ctr)+" CTR.");if(computed.fb.clicks>0||computed.ig.clicks>0)parts.push("Combined Meta engagement: "+fmt(m.clicks)+" clicks at "+fR(m.cpc)+" blended CPC.");if(t.clicks>0)parts.push("TikTok contributed "+fmt(t.clicks)+" clicks, with engagement signals amplifying organic distribution through TikTok\u2019s recommendation engine.");if(computed.fb.clicks===0&&computed.ig.clicks===0&&t.clicks===0)parts.push("No engagement data recorded for the selected campaigns in this date range.");if(m.cpc>0&&m.cpc<2)parts.push("Meta CPC below R2.00 is a positive efficiency signal \u2014 consider scaling budget on top-performing ad sets.");else if(m.cpc>5)parts.push("Meta CPC above R5.00 warrants creative review and potential audience refresh.");return parts.join(" ");})()}'''

c = c.replace(old_engagement, new_engagement)

with open("/workspaces/media-on-gas/dashboard/src/App.jsx", "w") as f:
    f.write(c)
print("Done - smart insights fixed")
