import re

old = '''function genFlags(m,t,camps){
  var fl=[],id=1;
  if(m.frequency>3.0)fl.push({id:id++,severity:m.frequency>4?"critical":"warning",platform:"Meta",metric:"Frequency",currentValue:m.frequency.toFixed(2)+"x",threshold:"3.0x",message:"Meta ad frequency has exceeded the optimal threshold. Audiences are seeing ads too often which can lead to ad fatigue.",recommendation:"Refresh creative assets or expand target audience to reduce repetition.",status:"open"});
  if(m.ctr>0&&m.ctr<1.0)fl.push({id:id++,severity:"warning",platform:"Meta",metric:"CTR",currentValue:pc(m.ctr),threshold:"1.00%",message:"Click-through rate is below the 1% benchmark indicating creative or targeting may not be resonating.",recommendation:"Test new ad creatives, headlines or audience segments. Consider A/B testing.",status:"open"});
  if(t.cpm>0&&m.cpm>0&&m.cpm/t.cpm>2.5)fl.push({id:id++,severity:"info",platform:"Cross-platform",metric:"CPM Delta",currentValue:(m.cpm/t.cpm).toFixed(1)+"x",threshold:"2.5x",message:"Meta CPM ("+fR(m.cpm)+") is significantly higher than TikTok ("+fR(t.cpm)+"). Evaluate budget allocation.",recommendation:"Consider shifting budget to TikTok for cost-efficient reach whilst maintaining Meta for precision targeting.",status:"open"});
  if(m.cpc>0&&m.cpc<2.0)fl.push({id:id++,severity:"positive",platform:"Meta",metric:"CPC",currentValue:fR(m.cpc),threshold:"R2.00",message:"Meta cost-per-click is below the R2.00 benchmark indicating strong creative efficiency.",recommendation:"Maintain current strategy and consider scaling budget on top ad sets.",status:"open"});
  if(t.follows>500)fl.push({id:id++,severity:"positive",platform:"TikTok",metric:"Community Growth",currentValue:fmt(t.follows)+" follows",threshold:"500",message:"TikTok follower acquisition is exceeding targets with strong audience resonance.",recommendation:"Continue current follower strategy and produce similar creative formats.",status:"open"});
  if(t.cpm>0&&t.cpm<10)fl.push({id:id++,severity:"positive",platform:"TikTok",metric:"CPM Efficiency",currentValue:fR(t.cpm),threshold:"R10.00",message:"TikTok delivering impressions at exceptional value below R10 CPM benchmark.",recommendation:"Maximise TikTok as primary scale channel.",status:"open"});
  camps.filter(function(c){return parseFloat(c.spend)>5000&&parseFloat(c.ctr||0)<0.8;}).forEach(function(c){fl.push({id:id++,severity:"warning",platform:c.platform||"Meta",metric:"Campaign CTR",currentValue:pc(parseFloat(c.ctr||0)),threshold:"0.80%",message:"Campaign '"+c.campaignName+"' has low CTR despite "+fR(parseFloat(c.spend))+" spend.",recommendation:"Review creative assets and targeting. Consider pausing underperforming ad sets.",status:"open"});});
  fl.sort(function(a,b){var o={critical:0,warning:1,info:2,positive:3};return(o[a.severity]||9)-(o[b.severity]||9);});
  return fl;
}'''

new = '''function genFlags(m,t,camps){
  var fl=[],id=1;
  var metaImpShare=m.impressions>0&&t.impressions>0?(m.impressions/(m.impressions+t.impressions)*100):0;
  var ttImpShare=t.impressions>0&&m.impressions>0?(t.impressions/(m.impressions+t.impressions)*100):0;
  var metaSpendShare=m.spend>0&&t.spend>0?(m.spend/(m.spend+t.spend)*100):0;
  var blendedCpc=(m.clicks+t.clicks)>0?(m.spend+t.spend)/(m.clicks+t.clicks):0;
  var cpfTT=t.follows>0?t.spend/t.follows:0;
  if(m.frequency>4.0)fl.push({id:id++,severity:"critical",platform:"Meta",metric:"Audience Saturation \u2014 Frequency",currentValue:m.frequency.toFixed(2)+"x",threshold:"4.0x",message:"Meta frequency has breached the critical 4.0x ceiling. At this level, diminishing returns accelerate sharply \u2014 each additional impression delivers progressively less incremental value whilst actively increasing the risk of negative brand sentiment and audience fatigue. Historical benchmarks show engagement rates typically decline 15-25% once frequency exceeds 4x in a single flight.",recommendation:"Immediately implement audience exclusion rules for users with 4+ impressions. Rotate in fresh creative assets to reset engagement curves. Consider splitting the budget across a broader Lookalike stack (1-3%, 3-5%, 5-10%) to access untapped reach pools whilst maintaining quality.",status:"open"});
  else if(m.frequency>3.0)fl.push({id:id++,severity:"warning",platform:"Meta",metric:"Frequency Pressure Building",currentValue:m.frequency.toFixed(2)+"x",threshold:"3.0x",message:"Meta frequency is approaching the fatigue threshold at "+m.frequency.toFixed(2)+"x. Whilst still within acceptable range for direct-response campaigns, sustained delivery at this level will erode CTR and inflate CPC within the next 3-5 days if audience pools are not refreshed.",recommendation:"Proactively expand audience size by layering in new interest-based or behavioural targeting segments. Schedule a creative rotation for the next 48 hours \u2014 even minor variations (colour shifts, headline swaps, thumbnail changes) can reset the frequency curve and extend the productive lifespan of the ad set.",status:"open"});
  if(m.ctr>0&&m.ctr<0.8)fl.push({id:id++,severity:"critical",platform:"Meta",metric:"Engagement Deficit \u2014 CTR",currentValue:pc(m.ctr),threshold:"0.80%",message:"Meta CTR at "+pc(m.ctr)+" is significantly below the 0.80% floor for paid social in the South African market. This indicates a fundamental disconnect between the creative message and the target audience \u2014 the ads are being served but failing to generate meaningful intent signals. Low CTR also degrades Meta\u2019s quality ranking, which compounds the problem by increasing CPM.",recommendation:"Conduct an immediate creative audit: review thumb-stop rates (are users pausing?), hook completion rates (are they watching past 3 seconds?), and CTA click-through. Test UGC-style creative against polished brand assets \u2014 UGC typically outperforms by 30-50% on CTR in the ZA market. Verify audience-message alignment: are you showing data deals to data-hungry segments, or mismatching offers?",status:"open"});
  else if(m.ctr>0&&m.ctr<1.2)fl.push({id:id++,severity:"warning",platform:"Meta",metric:"CTR Below Benchmark",currentValue:pc(m.ctr),threshold:"1.20%",message:"Meta CTR at "+pc(m.ctr)+" is below the 1.20% benchmark for optimised paid social campaigns. Whilst not critical, this suggests room for creative or targeting refinement that could materially improve downstream conversion efficiency.",recommendation:"A/B test three creative variations: (1) different opening hooks in the first 2 seconds, (2) stronger value proposition in the primary text, (3) more urgent or specific CTA copy. Also test narrowing the audience to higher-intent segments \u2014 a smaller but more engaged audience often delivers better blended ROI than broad reach with weak engagement.",status:"open"});
  if(m.cpc>0&&m.cpc>5.0)fl.push({id:id++,severity:"critical",platform:"Meta",metric:"Cost Efficiency Alert \u2014 CPC",currentValue:fR(m.cpc),threshold:"R5.00",message:"Meta CPC at "+fR(m.cpc)+" has exceeded the R5.00 efficiency ceiling. At this rate, the cost to drive each click is eroding campaign ROI and suggests either creative fatigue, audience saturation, or competitive auction pressure in the targeted segments.",recommendation:"Shift budget allocation toward your lowest-CPC ad sets immediately. Pause any ad sets with CPC above "+fR(m.cpc*1.2)+" and reallocate to proven performers. Test Advantage+ placements to access lower-cost inventory across Reels, Stories, and the Audience Network. Consider bid cap strategies to enforce CPC discipline.",status:"open"});
  if(t.cpm>0&&m.cpm>0){var cpmRatio=m.cpm/t.cpm;if(cpmRatio>3.0)fl.push({id:id++,severity:"warning",platform:"Cross-platform",metric:"Platform Efficiency Gap \u2014 CPM",currentValue:cpmRatio.toFixed(1)+"x differential",threshold:"3.0x",message:"Meta is delivering impressions at "+fR(m.cpm)+" CPM versus TikTok\u2019s "+fR(t.cpm)+" CPM \u2014 a "+cpmRatio.toFixed(1)+"x cost differential. Whilst Meta\u2019s higher CPM reflects richer targeting data and stronger attribution, a gap this wide warrants strategic budget rebalancing to optimise overall campaign efficiency.",recommendation:"Model a 10-15% budget shift from Meta awareness campaigns to TikTok, maintaining Meta\u2019s allocation for conversion and retargeting objectives where its attribution advantage justifies the premium. Run a two-week test comparing blended CPA across both allocation models before committing to a permanent shift."});
  else if(cpmRatio>2.0)fl.push({id:id++,severity:"info",platform:"Cross-platform",metric:"CPM Variance Across Platforms",currentValue:cpmRatio.toFixed(1)+"x differential",threshold:"2.0x",message:"Meta CPM ("+fR(m.cpm)+") runs "+cpmRatio.toFixed(1)+"x higher than TikTok ("+fR(t.cpm)+"). This is within normal range for a dual-platform strategy where Meta handles precision targeting and TikTok drives scale, but worth monitoring as the gap widens.",recommendation:"Continue monitoring the CPM delta weekly. If it exceeds 3x, evaluate whether Meta\u2019s higher-funnel campaigns (awareness, reach) could be more efficiently served on TikTok, reserving Meta budget for mid-to-lower funnel objectives where its measurement stack provides clearer ROI visibility.",status:"open"});}
  if(metaSpendShare>75&&ttImpShare>50)fl.push({id:id++,severity:"info",platform:"Cross-platform",metric:"Budget-to-Impression Imbalance",currentValue:metaSpendShare.toFixed(0)+"% spend on Meta",threshold:"75%",message:"Meta is consuming "+metaSpendShare.toFixed(0)+"% of budget but TikTok is delivering "+ttImpShare.toFixed(0)+"% of impressions. This suggests TikTok is significantly more capital-efficient for reach, and the current allocation may be over-indexing on Meta for awareness objectives.",recommendation:"Review whether Meta\u2019s outsized budget share is justified by conversion performance. If Meta is driving the majority of measurable conversions, the allocation is correct. If both platforms serve primarily awareness objectives, rebalance toward TikTok\u2019s superior impression economics.",status:"open"});
  if(m.cpc>0&&m.cpc<1.50)fl.push({id:id++,severity:"positive",platform:"Meta",metric:"Strong Click Efficiency",currentValue:fR(m.cpc),threshold:"R1.50",message:"Meta CPC at "+fR(m.cpc)+" is operating well below the R1.50 efficiency benchmark for South African paid social. This indicates excellent creative-audience fit \u2014 the algorithm has identified high-intent audience pockets and the creative is converting attention into action at an efficient rate.",recommendation:"This is a scale signal. Increase daily budgets by 15-20% on the top-performing ad sets to capitalise on the efficient delivery window before auction dynamics shift. Document the winning creative elements (hook, format, CTA) for replication across future campaigns.",status:"open"});
  else if(m.cpc>0&&m.cpc<3.0)fl.push({id:id++,severity:"positive",platform:"Meta",metric:"CPC Within Target Range",currentValue:fR(m.cpc),threshold:"R3.00",message:"Meta CPC at "+fR(m.cpc)+" is within the healthy R1.50-R3.00 range for direct-response campaigns in the SA market, confirming effective creative and audience targeting.",recommendation:"Maintain current optimisation approach. Focus on incremental improvements: test new ad formats (Reels, carousel) against current winners, and expand Lookalike audiences from 1% to 2-3% to increase addressable reach without sacrificing click quality.",status:"open"});
  if(t.follows>1000){var cpf=t.spend/t.follows;fl.push({id:id++,severity:"positive",platform:"TikTok",metric:"Community Acquisition Momentum",currentValue:fmt(t.follows)+" follows at "+fR(cpf)+" CPF",threshold:"1,000 follows",message:"TikTok has acquired "+fmt(t.follows)+" followers at "+fR(cpf)+" cost-per-follow. This community represents a compounding organic asset \u2014 each follower increases future organic reach, reduces paid media dependency, and provides a retargetable first-party audience for subsequent campaigns.",recommendation:"Accelerate community investment. The current CPF of "+fR(cpf)+" is below market rates for quality follower acquisition. Consider allocating an additional 10-15% of TikTok budget specifically to follower campaigns whilst the creative is resonating. Every follower acquired now reduces future paid reach costs.",status:"open"});}
  else if(t.follows>200)fl.push({id:id++,severity:"positive",platform:"TikTok",metric:"Community Growth Active",currentValue:fmt(t.follows)+" follows",threshold:"200",message:"TikTok follower acquisition is tracking positively with "+fmt(t.follows)+" new follows in the period. Building owned audience on TikTok reduces long-term paid media dependency.",recommendation:"Continue current follower strategy. Test creator-led content and trending audio formats to accelerate organic follow rates alongside paid acquisition.",status:"open"});
  if(t.cpm>0&&t.cpm<8)fl.push({id:id++,severity:"positive",platform:"TikTok",metric:"Exceptional Impression Value",currentValue:fR(t.cpm)+" CPM",threshold:"R8.00",message:"TikTok is delivering impressions at "+fR(t.cpm)+" CPM \u2014 significantly below the R8.00 benchmark for the South African market. At this rate, every R1,000 buys approximately "+fmt(Math.round(1000/t.cpm*1000))+" impressions, making TikTok the most capital-efficient awareness channel in the campaign.",recommendation:"Maximise TikTok as the primary scale and awareness channel. This CPM level typically indicates strong content relevance scores and favourable auction positioning \u2014 the algorithm is rewarding the creative quality. Increase investment to capture this efficiency window before competitive pressure normalises rates.",status:"open"});
  else if(t.cpm>0&&t.cpm<15)fl.push({id:id++,severity:"positive",platform:"TikTok",metric:"Competitive CPM",currentValue:fR(t.cpm)+" CPM",threshold:"R15.00",message:"TikTok CPM at "+fR(t.cpm)+" is within the efficient range for paid social in South Africa, confirming good content-audience alignment.",recommendation:"Monitor CPM trends weekly. If CPM begins rising above R15, review creative freshness and audience targeting for signs of saturation.",status:"open"});
  camps.filter(function(c){return parseFloat(c.spend)>3000;}).forEach(function(c){
    var cCtr=parseFloat(c.ctr||0);var cCpc=parseFloat(c.cpc||0);var cSpend=parseFloat(c.spend);var cImps=parseFloat(c.impressions||0);
    if(cCtr<0.6&&cImps>10000)fl.push({id:id++,severity:"critical",platform:c.platform||"Meta",metric:"Underperforming Campaign",currentValue:pc(cCtr)+" CTR on "+fR(cSpend),threshold:"0.60% CTR",message:"Campaign \u2018"+c.campaignName+"\u2019 is delivering "+pc(cCtr)+" CTR with "+fR(cSpend)+" invested against "+fmt(cImps)+" impressions. This level of engagement failure with meaningful spend indicates a structural issue with either creative relevance, audience targeting, or landing page experience.",recommendation:"Conduct a three-part diagnostic: (1) Creative \u2014 are the first 3 seconds compelling enough to stop the scroll? (2) Audience \u2014 is the targeting aligned with the offer? (3) Landing page \u2014 does the destination match the ad promise? Pause the lowest-performing ad sets and reallocate budget to campaigns delivering above "+pc(1.0)+" CTR.",status:"open"});
    else if(cCtr<1.0&&cImps>5000)fl.push({id:id++,severity:"warning",platform:c.platform||"Meta",metric:"Below-Benchmark Campaign",currentValue:pc(cCtr)+" CTR",threshold:"1.00%",message:"Campaign \u2018"+c.campaignName+"\u2019 at "+pc(cCtr)+" CTR is underperforming against the 1.0% benchmark with "+fR(cSpend)+" spend.",recommendation:"Review the top 3 ad creatives within this campaign. Replace the lowest performer with a new variant testing a different hook, format, or value proposition.",status:"open"});
    if(cCpc>8&&c.platform==="Meta")fl.push({id:id++,severity:"warning",platform:"Meta",metric:"High CPC Campaign",currentValue:fR(cCpc)+" CPC",threshold:"R8.00",message:"Campaign \u2018"+c.campaignName+"\u2019 is running at "+fR(cCpc)+" CPC, well above the efficient range. This inflated cost-per-click is dragging down the blended account CPC.",recommendation:"Review the bid strategy on this campaign. Switch from lowest-cost to cost-cap bidding with a target CPC of "+fR(cCpc*0.6)+". If performance doesn\u2019t improve within 48 hours, consolidate this campaign\u2019s budget into higher-performing campaigns.",status:"open"});
  });
  if(blendedCpc>0&&blendedCpc<2.0)fl.push({id:id++,severity:"positive",platform:"Cross-platform",metric:"Blended Cost Efficiency",currentValue:fR(blendedCpc)+" blended CPC",threshold:"R2.00",message:"The cross-platform blended CPC of "+fR(blendedCpc)+" confirms the multi-channel strategy is delivering cost-efficient engagement. The combination of Meta\u2019s targeted clicks and TikTok\u2019s volume-driven engagement is optimising the overall cost base.",recommendation:"This efficiency level supports budget scaling. Model a 15-20% budget increase across both platforms and monitor whether the blended CPC holds below R2.00 \u2014 if it does, the campaign has room to grow without sacrificing efficiency.",status:"open"});
  fl.sort(function(a,b){var o={critical:0,warning:1,info:2,positive:3};return(o[a.severity]||9)-(o[b.severity]||9);});
  return fl;
}'''

with open("/workspaces/media-on-gas/dashboard/src/App.jsx", "r") as f:
    content = f.read()

content = content.replace(old, new)

with open("/workspaces/media-on-gas/dashboard/src/App.jsx", "w") as f:
    f.write(content)

print("Done - flags upgraded")
