with open("/workspaces/media-on-gas/dashboard/src/App.jsx", "r") as f:
    c = f.read()

# Fix 1: Summary glass labels
c = c.replace('>APP STORE CLICKS<', '>CLICKS TO APP INSTALL<')
c = c.replace('>LP CLICKS<', '>CLICKS TO LANDING PAGE<')
c = c.replace('>LEADS<', '>LEADS<')
c = c.replace('>FOLLOWS<', '>FOLLOWS<')
c = c.replace('>PAGE LIKES<', '>LIKES<')

# Fix 2: Sort rows by platform then objective in the table
c = c.replace(
    """var rows=sel.map(function(camp){
                var obj=getObj(camp.campaignName);var result=getResult(camp,obj);var spend=parseFloat(camp.spend||0);var clicks=parseFloat(camp.clicks||0);var costPer=result>0?spend/result:0;var convRate=clicks>0&&obj==="Leads"?(parseFloat(camp.leads||0)/clicks*100):0;
                return{name:camp.campaignName,platform:camp.platform,objective:obj,spend:spend,clicks:clicks,result:result,resultLabel:getResultLabel(obj),costPer:costPer,costLabel:getCostLabel(obj),convRate:convRate};
              });""",
    """var rows=sel.map(function(camp){
                var obj=getObj(camp.campaignName);var result=getResult(camp,obj);var spend=parseFloat(camp.spend||0);var clicks=parseFloat(camp.clicks||0);var costPer=result>0?spend/result:0;var convRate=clicks>0&&obj==="Leads"?(parseFloat(camp.leads||0)/clicks*100):0;
                return{name:camp.campaignName,platform:camp.platform,objective:obj,spend:spend,clicks:clicks,result:result,resultLabel:getResultLabel(obj),costPer:costPer,costLabel:getCostLabel(obj),convRate:convRate};
              });
              var platOrder={"Facebook":0,"Instagram":1,"TikTok":2};
              var objOrder={"App Store Clicks":0,"Landing Page Clicks":1,"Leads":2,"Follows":3,"Page Likes":4,"Traffic":5};
              rows.sort(function(a,b){var p=platOrder[a.platform]||9;var q=platOrder[b.platform]||9;if(p!==q)return p-q;return (objOrder[a.objective]||9)-(objOrder[b.objective]||9);});"""
)

# Fix 3: Upgrade all overview insights to expert level

# Awareness insight
old_awareness = """{(function(){var parts=[];parts.push("The selected campaigns have served "+fmt(computed.totalImps)+" total impressions against "+fR(computed.totalSpend)+" investment at "+fR(computed.blendedCpm)+" blended CPM.");if(computed.fb.impressions>0)parts.push("Facebook delivered "+fmt(computed.fb.impressions)+" impressions reaching "+fmt(computed.fb.reach)+" unique people at "+computed.fb.frequency.toFixed(2)+"x frequency and "+fR(computed.fb.cpm)+" CPM.");if(computed.ig.impressions>0)parts.push("Instagram contributed "+fmt(computed.ig.impressions)+" impressions reaching "+fmt(computed.ig.reach)+" unique people at "+fR(computed.ig.cpm)+" CPM.");if(t.impressions>0)parts.push("TikTok delivered "+fmt(t.impressions)+" impressions at "+fR(t.cpm)+" CPM, the most cost-efficient impression channel in the campaign.");return parts.join(" ");})()}"""

new_awareness = """{(function(){var parts=[];var totalReach=computed.fb.reach+computed.ig.reach+t.reach;parts.push("The campaign\\'s awareness architecture has delivered "+fmt(computed.totalImps)+" impressions across "+(computed.fb.impressions>0?"Facebook":"")+(computed.ig.impressions>0?", Instagram":"")+(t.impressions>0?" and TikTok":"")+" against "+fR(computed.totalSpend)+" media investment, achieving a blended CPM of "+fR(computed.blendedCpm)+".");if(computed.fb.impressions>0){var fbShare=computed.totalImps>0?(computed.fb.impressions/computed.totalImps*100).toFixed(1):"0";parts.push("Facebook commands "+fbShare+"% of total impression volume with "+fmt(computed.fb.impressions)+" impressions reaching "+fmt(computed.fb.reach)+" unique individuals at "+computed.fb.frequency.toFixed(2)+"x frequency. At "+fR(computed.fb.cpm)+" CPM, the platform delivers premium inventory with superior audience measurement and attribution capabilities.");}if(computed.ig.impressions>0){var igShare=computed.totalImps>0?(computed.ig.impressions/computed.totalImps*100).toFixed(1):"0";parts.push("Instagram represents "+igShare+"% of impressions with "+fmt(computed.ig.impressions)+" served to "+fmt(computed.ig.reach)+" unique users at "+fR(computed.ig.cpm)+" CPM"+(computed.ig.cpm<computed.fb.cpm&&computed.fb.cpm>0?", "+(((computed.fb.cpm-computed.ig.cpm)/computed.fb.cpm)*100).toFixed(0)+"% more cost-efficient than Facebook per thousand impressions":"")+".");}if(t.impressions>0){var ttShare=computed.totalImps>0?(t.impressions/computed.totalImps*100).toFixed(1):"0";parts.push("TikTok delivers "+ttShare+"% of all campaign impressions at "+fR(t.cpm)+" CPM"+(t.reach>0?", reaching "+fmt(t.reach)+" users":"")+(computed.fb.cpm>0&&t.cpm>0?". At "+(computed.fb.cpm/t.cpm).toFixed(1)+"x more cost-efficient than Facebook, TikTok serves as the campaign\\'s primary scale engine for mass awareness delivery":"")+".");}if(totalReach>0)parts.push("The combined cross-platform reach of "+fmt(totalReach)+" unique individuals represents the campaign\\'s total addressable audience footprint for this period.");return parts.join(" ");})()}"""

c = c.replace(old_awareness, new_awareness)

# Engagement insight
old_engagement = """{(function(){var parts=[];if(computed.fb.clicks>0)parts.push("Facebook generated "+fmt(computed.fb.clicks)+" clicks at "+fR(computed.fb.cpc)+" CPC with "+pc(computed.fb.ctr)+" CTR, confirming strong creative-audience alignment.");if(computed.ig.clicks>0)parts.push("Instagram contributed "+fmt(computed.ig.clicks)+" clicks at "+fR(computed.ig.cpc)+" CPC with "+pc(computed.ig.ctr)+" CTR.");if(computed.fb.clicks>0||computed.ig.clicks>0)parts.push("Combined Meta engagement: "+fmt(m.clicks)+" clicks at "+fR(m.cpc)+" blended CPC.");if(t.clicks>0)parts.push("TikTok contributed "+fmt(t.clicks)+" clicks, with engagement signals amplifying organic distribution through TikTok\\u2019s recommendation engine.");if(computed.fb.clicks===0&&computed.ig.clicks===0&&t.clicks===0)parts.push("No engagement data recorded for the selected campaigns in this date range.");return parts.join(" ");})()}"""

new_engagement = """{(function(){var parts=[];var totalClicks=m.clicks+t.clicks;var blendedCpc=totalClicks>0?computed.totalSpend/totalClicks:0;if(computed.fb.clicks>0){var fbClickShare=totalClicks>0?(computed.fb.clicks/totalClicks*100).toFixed(1):"0";parts.push("Facebook drives "+fbClickShare+"% of total click volume with "+fmt(computed.fb.clicks)+" clicks at "+fR(computed.fb.cpc)+" CPC and "+pc(computed.fb.ctr)+" CTR. "+(computed.fb.ctr>3?"The above-3% CTR indicates exceptional creative resonance, the campaign creative is actively capturing audience attention beyond standard benchmarks.":computed.fb.ctr>1.5?"The CTR confirms healthy engagement levels, the audience is responding positively to the creative messaging.":""));}if(computed.ig.clicks>0){parts.push("Instagram contributed "+fmt(computed.ig.clicks)+" clicks at "+fR(computed.ig.cpc)+" CPC with "+pc(computed.ig.ctr)+" CTR."+(computed.ig.cpc<computed.fb.cpc&&computed.fb.cpc>0?" Instagram\\'s lower CPC makes it a more cost-efficient click driver than Facebook for this campaign.":""));}if(computed.fb.clicks>0||computed.ig.clicks>0){parts.push("The combined Meta platform engagement totals "+fmt(m.clicks)+" clicks at "+fR(m.cpc)+" blended CPC, representing the primary engagement engine for measurable intent conversion.");}if(t.clicks>0){parts.push("TikTok generated "+fmt(t.clicks)+" clicks"+(t.cpc>0?" at "+fR(t.cpc)+" CPC":"")+(t.ctr>0?" with "+pc(t.ctr)+" CTR":"")+". TikTok engagement carries additional amplification value as the algorithm promotes content with strong interaction signals, extending reach beyond the paid audience.");}if(totalClicks>0)parts.push("The cross-platform blended CPC of "+fR(blendedCpc)+" across "+fmt(totalClicks)+" total clicks confirms efficient conversion of awareness impressions into actionable engagement signals.");if(totalClicks===0)parts.push("No click engagement recorded for the selected campaigns in this date range. This may indicate the campaigns are optimised for awareness rather than direct-response objectives.");return parts.join(" ");})()}"""

c = c.replace(old_engagement, new_engagement)

# Objective insight
old_obj_insight = """{(function(){var p=[];p.push("The selected campaigns invested "+fR(allSpend)+" generating "+fmt(allClicks)+" total clicks across all objectives.");if(tApp>0)p.push("App Store click campaigns delivered "+fmt(tApp)+" clicks at "+fR(sApp/tApp)+" CPC.");if(tLp>0)p.push("Landing page campaigns drove "+fmt(tLp)+" clicks at "+fR(sLp/tLp)+" CPC.");if(tLeads>0){var lClicks=rows.filter(function(r){return r.objective==="Leads";}).reduce(function(a,r){return a+r.clicks;},0);p.push("Lead generation produced "+fmt(tLeads)+" leads at "+fR(sLeads/tLeads)+" CPL"+(lClicks>0?", a "+(tLeads/lClicks*100).toFixed(1)+"% conversion rate.":"."));}if(tFollows>0)p.push("Follower campaigns acquired "+fmt(tFollows)+" new followers at "+fR(sFollows/tFollows)+" CPF.");if(tLikes>0)p.push("Page like campaigns earned "+fmt(tLikes)+" new likes at "+fR(sLikes/tLikes)+" cost per like.");return p.join(" ");})()}"""

new_obj_insight = """{(function(){var p=[];p.push("The selected campaigns have deployed "+fR(allSpend)+" across "+sel.length+" campaign placements, generating "+fmt(allClicks)+" total measurable actions.");if(tApp>0){p.push("App install campaigns delivered "+fmt(tApp)+" clicks to the app store at "+fR(sApp/tApp)+" cost per click. Each click represents a user driven to the point of installation, the final measurable step before conversion in the app acquisition funnel.");}if(tLp>0){p.push("Landing page campaigns generated "+fmt(tLp)+" qualified visits at "+fR(sLp/tLp)+" cost per visit, driving high-intent traffic to destination pages for further conversion.");}if(tLeads>0){var lClicks=rows.filter(function(r){return r.objective==="Leads";}).reduce(function(a,r){return a+r.clicks;},0);var convR=lClicks>0?(tLeads/lClicks*100).toFixed(1):"0";p.push("Lead generation campaigns produced "+fmt(tLeads)+" qualified leads at "+fR(sLeads/tLeads)+" cost per lead"+(lClicks>0?", converting "+convR+"% of "+fmt(lClicks)+" clicks into form submissions. "+(parseFloat(convR)>5?"The above-5% conversion rate indicates strong alignment between ad creative, audience targeting, and landing page experience.":"The conversion rate suggests potential to optimise the landing page experience to improve click-to-lead conversion."):".")+"");}if(tFollows>0){p.push("Community growth campaigns acquired "+fmt(tFollows)+" new followers at "+fR(sFollows/tFollows)+" cost per follow. Each follower represents a compounding organic asset that increases future content reach and reduces long-term paid media dependency.");}if(tLikes>0){p.push("Page engagement campaigns earned "+fmt(tLikes)+" new page likes at "+fR(sLikes/tLikes)+" per like, strengthening organic reach capacity and social proof signals that enhance paid ad performance.");}if(allClicks===0)p.push("No measurable objective actions recorded in this date range. Verify campaign delivery status and objective configuration.");return p.join(" ");})()}"""

c = c.replace(old_obj_insight, new_obj_insight)

with open("/workspaces/media-on-gas/dashboard/src/App.jsx", "w") as f:
    f.write(c)
print("Done - labels, sort, and expert insights fixed")
