with open("/workspaces/media-on-gas/dashboard/src/App.jsx", "r") as f:
    c = f.read()

# Find and replace the overview tab content
start_marker = "{tab===\"overview\"&&(<div>"
end_marker = "{tab===\"tof\"&&(<div>"

si = c.find(start_marker)
ei = c.find(end_marker)

if si < 0 or ei < 0:
    print("ERROR: Could not find overview tab markers")
    print("start found:", si)
    print("end found:", ei)
else:
    # Find the closing tags between overview and tof
    # We need to go back from ei to find the proper closing
    before = c[:si]
    after = c[ei:]
    
    overview = """{tab==="overview"&&(<div>

          <SH icon={Ic.chart(P.orchid,20)} title="Campaign Overview" sub={df+" to "+dt+" \\u00b7 "+selected.length+" campaigns \\u00b7 Funnel Performance Report"} accent={P.orchid}/>

          {/* ═══ AWARENESS ASSESSMENT ═══ */}
          <div style={{background:"linear-gradient(135deg, #003a55 0%, #004F71 50%, #005580 100%)",borderRadius:18,padding:"6px 24px 24px",marginBottom:28,border:"1px solid rgba(255,203,5,0.15)"}}>
            <div style={{textAlign:"center",padding:"18px 0 16px"}}><span style={{fontSize:18,fontWeight:900,color:"#fff",fontFamily:ff,letterSpacing:1}}>AWARENESS ASSESSMENT</span><div style={{fontSize:10,color:"rgba(255,255,255,0.5)",fontFamily:fm,marginTop:4,letterSpacing:3}}>TOP OF FUNNEL</div></div>

            <table style={{width:"100%",borderCollapse:"collapse",marginBottom:16}}>
              <thead><tr>{["","Media Spend","Impressions","Reach","CPM","Frequency"].map(function(h,i){return <th key={i} style={{padding:"10px 12px",fontSize:9,fontWeight:700,textTransform:"uppercase",color:"#FFCB05",textAlign:i===0?"left":"center",background:"#003a55",border:"1px solid #002a40",fontFamily:fm,letterSpacing:1}}>{h}</th>;})}</tr></thead>
              <tbody>
                <tr style={{background:"rgba(69,153,255,0.08)"}}><td style={{padding:"12px",border:"1px solid #002a40",display:"flex",alignItems:"center",gap:8}}><span style={{width:10,height:10,borderRadius:"50%",background:P.fb}}></span><span style={{fontSize:12,fontWeight:700,color:"#fff"}}>Facebook</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#fff",fontFamily:fm,fontSize:13,fontWeight:700}}>{fR(computed.fb.spend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#fff",fontFamily:fm,fontSize:13}}>{fmt(computed.fb.impressions)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#fff",fontFamily:fm,fontSize:13}}>{fmt(computed.fb.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:computed.fb.cpm<15?P.mint:P.warning,fontFamily:fm,fontSize:13,fontWeight:700}}>{fR(computed.fb.cpm)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:computed.fb.frequency>3?P.warning:"#fff",fontFamily:fm,fontSize:13,fontWeight:700}}>{computed.fb.frequency>0?computed.fb.frequency.toFixed(2)+"x":"\\u2014"}</td></tr>
                <tr style={{background:"rgba(225,48,108,0.08)"}}><td style={{padding:"12px",border:"1px solid #002a40",display:"flex",alignItems:"center",gap:8}}><span style={{width:10,height:10,borderRadius:"50%",background:P.ig}}></span><span style={{fontSize:12,fontWeight:700,color:"#fff"}}>Instagram</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#fff",fontFamily:fm,fontSize:13,fontWeight:700}}>{fR(computed.ig.spend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#fff",fontFamily:fm,fontSize:13}}>{fmt(computed.ig.impressions)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#fff",fontFamily:fm,fontSize:13}}>{fmt(computed.ig.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:computed.ig.cpm<15?P.mint:P.warning,fontFamily:fm,fontSize:13,fontWeight:700}}>{fR(computed.ig.cpm)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:computed.ig.frequency>3?P.warning:"#fff",fontFamily:fm,fontSize:13,fontWeight:700}}>{computed.ig.frequency>0?computed.ig.frequency.toFixed(2)+"x":"\\u2014"}</td></tr>
                <tr style={{background:"rgba(69,153,255,0.15)"}}><td style={{padding:"12px",border:"1px solid #002a40"}}><span style={{fontSize:12,fontWeight:900,color:P.fb}}>Meta Total</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{fR(m.spend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{fmt(m.impressions)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{fmt(m.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{fR(m.cpm)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{m.frequency>0?m.frequency.toFixed(2)+"x":"\\u2014"}</td></tr>
                <tr style={{background:"rgba(0,242,234,0.08)"}}><td style={{padding:"12px",border:"1px solid #002a40",display:"flex",alignItems:"center",gap:8}}><span style={{width:10,height:10,borderRadius:"50%",background:P.tt}}></span><span style={{fontSize:12,fontWeight:700,color:"#fff"}}>TikTok</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#fff",fontFamily:fm,fontSize:13,fontWeight:700}}>{fR(t.spend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#fff",fontFamily:fm,fontSize:13}}>{fmt(t.impressions)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#fff",fontFamily:fm,fontSize:13}}>\\u2014</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:t.cpm<15?P.mint:P.warning,fontFamily:fm,fontSize:13,fontWeight:700}}>{fR(t.cpm)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#fff",fontFamily:fm,fontSize:13}}>\\u2014</td></tr>
                <tr style={{background:"rgba(255,107,0,0.15)"}}><td style={{padding:"12px",border:"1px solid #002a40"}}><span style={{fontSize:13,fontWeight:900,color:"#FFCB05"}}>GRAND TOTAL</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#FFCB05",fontFamily:fm,fontSize:15,fontWeight:900}}>{fR(computed.totalSpend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#FFCB05",fontFamily:fm,fontSize:15,fontWeight:900}}>{fmt(computed.totalImps)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#FFCB05",fontFamily:fm,fontSize:15,fontWeight:900}}>{fmt(computed.grand.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#FFCB05",fontFamily:fm,fontSize:15,fontWeight:900}}>{fR(computed.blendedCpm)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#FFCB05",fontFamily:fm,fontSize:15,fontWeight:900}}>{computed.grand.frequency>0?computed.grand.frequency.toFixed(2)+"x":"\\u2014"}</td></tr>
              </tbody>
            </table>

            <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,marginBottom:16}}>
              <div style={{background:"rgba(0,0,0,0.2)",borderRadius:12,padding:20}}><div style={{fontSize:10,fontWeight:800,color:"rgba(255,255,255,0.5)",letterSpacing:3,fontFamily:fm,textTransform:"uppercase",marginBottom:14}}>Impressions & Reach by Platform</div><ResponsiveContainer width="100%" height={200}><BarChart data={[{name:"Facebook",Impressions:computed.fb.impressions,Reach:computed.fb.reach},{name:"Instagram",Impressions:computed.ig.impressions,Reach:computed.ig.reach},{name:"TikTok",Impressions:t.impressions,Reach:0}]} barSize={20}><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.1)"/><XAxis dataKey="name" tick={{fontSize:11,fill:"#fff",fontFamily:fm}} stroke="transparent"/><YAxis tick={{fontSize:10,fill:"rgba(255,255,255,0.4)",fontFamily:fm}} stroke="transparent" tickFormatter={function(v){return fmt(v);}}/><Tooltip content={Tip}/><Bar dataKey="Impressions" fill={P.cyan} radius={[6,6,0,0]}/><Bar dataKey="Reach" fill={P.orchid} radius={[6,6,0,0]}/></BarChart></ResponsiveContainer><div style={{display:"flex",justifyContent:"center",gap:16,marginTop:8}}><div style={{display:"flex",alignItems:"center",gap:4}}><span style={{width:8,height:8,borderRadius:2,background:P.cyan}}></span><span style={{fontSize:10,color:"rgba(255,255,255,0.6)",fontFamily:fm}}>Impressions</span></div><div style={{display:"flex",alignItems:"center",gap:4}}><span style={{width:8,height:8,borderRadius:2,background:P.orchid}}></span><span style={{fontSize:10,color:"rgba(255,255,255,0.6)",fontFamily:fm}}>Reach</span></div></div></div>
              <div style={{background:"rgba(0,0,0,0.2)",borderRadius:12,padding:20}}><div style={{fontSize:10,fontWeight:800,color:"rgba(255,255,255,0.5)",letterSpacing:3,fontFamily:fm,textTransform:"uppercase",marginBottom:14}}>Spend Allocation</div><ResponsiveContainer width="100%" height={200}><PieChart><Pie data={[{name:"Facebook",value:computed.fb.spend},{name:"Instagram",value:computed.ig.spend},{name:"TikTok",value:t.spend}]} cx="50%" cy="50%" outerRadius={72} innerRadius={44} paddingAngle={4} dataKey="value" stroke="none"><Cell fill={P.fb}/><Cell fill={P.ig}/><Cell fill={P.tt}/></Pie><Tooltip content={Tip}/></PieChart></ResponsiveContainer><div style={{display:"flex",justifyContent:"center",gap:12,marginTop:8}}>{[{n:"FB",v:computed.fb.spend,c:P.fb},{n:"IG",v:computed.ig.spend,c:P.ig},{n:"TT",v:t.spend,c:P.tt}].map(function(p){return <div key={p.n} style={{display:"flex",alignItems:"center",gap:4}}><span style={{width:8,height:8,borderRadius:"50%",background:p.c}}></span><span style={{fontSize:10,color:"rgba(255,255,255,0.6)",fontFamily:fm}}>{p.n} {fR(p.v)}</span></div>;})}</div></div>
            </div>

            <Insight title="Awareness Analysis" accent={P.cyan} icon={Ic.eye(P.cyan,16)}>The campaign has served <strong>{fmt(computed.totalImps)} impressions</strong> across Facebook ({fmt(computed.fb.impressions)}), Instagram ({fmt(computed.ig.impressions)}), and TikTok ({fmt(t.impressions)}) against <strong>{fR(computed.totalSpend)}</strong> total investment. Facebook delivers the richest audience data with {fmt(computed.fb.reach)} unique reach at {computed.fb.frequency>0?computed.fb.frequency.toFixed(2)+"x":"N/A"} frequency, whilst TikTok provides the most cost-efficient impressions at {fR(t.cpm)} CPM. The blended campaign CPM of <strong>{fR(computed.blendedCpm)}</strong> represents strong media value in the South African paid social market. {computed.fb.frequency>3?"Warning: Facebook frequency at "+computed.fb.frequency.toFixed(2)+"x is approaching the fatigue threshold \\u2014 consider audience expansion or creative refresh.":""}</Insight>
          </div>

          {/* \\u2550\\u2550\\u2550 ENGAGEMENT ASSESSMENT \\u2550\\u2550\\u2550 */}
          <div style={{background:P.glass,borderRadius:18,padding:"6px 24px 24px",marginBottom:28,border:"1px solid "+P.rule}}>
            <div style={{textAlign:"center",padding:"18px 0 16px"}}><span style={{fontSize:18,fontWeight:900,color:P.txt,fontFamily:ff,letterSpacing:1}}>ENGAGEMENT ASSESSMENT</span><div style={{fontSize:10,color:P.sub,fontFamily:fm,marginTop:4,letterSpacing:3}}>MIDDLE OF FUNNEL</div></div>

            <table style={{width:"100%",borderCollapse:"collapse",marginBottom:16}}>
              <thead><tr>{["","Media Spend","Reach","Clicks","CTR %","CPC"].map(function(h,i){return <th key={i} style={{padding:"10px 12px",fontSize:9,fontWeight:700,textTransform:"uppercase",color:"#FFCB05",textAlign:i===0?"left":"center",background:"#004F71",border:"1px solid #003a55",fontFamily:fm,letterSpacing:1}}>{h}</th>;})}</tr></thead>
              <tbody>
                <tr style={{background:"rgba(69,153,255,0.06)"}}><td style={{padding:"12px",border:"1px solid "+P.rule,display:"flex",alignItems:"center",gap:8}}><span style={{width:10,height:10,borderRadius:"50%",background:P.fb}}></span><span style={{fontSize:12,fontWeight:700,color:P.txt}}>Facebook</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13,fontWeight:700}}>{fR(computed.fb.spend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13}}>{fmt(computed.fb.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13,fontWeight:700}}>{fmt(computed.fb.clicks)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:computed.fb.ctr>2?P.mint:computed.fb.ctr>1?P.txt:P.warning,fontFamily:fm,fontSize:13,fontWeight:700}}>{pc(computed.fb.ctr)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:computed.fb.cpc<2?P.mint:P.txt,fontFamily:fm,fontSize:13,fontWeight:700}}>{fR(computed.fb.cpc)}</td></tr>
                <tr style={{background:"rgba(225,48,108,0.06)"}}><td style={{padding:"12px",border:"1px solid "+P.rule,display:"flex",alignItems:"center",gap:8}}><span style={{width:10,height:10,borderRadius:"50%",background:P.ig}}></span><span style={{fontSize:12,fontWeight:700,color:P.txt}}>Instagram</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13,fontWeight:700}}>{fR(computed.ig.spend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13}}>{fmt(computed.ig.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13,fontWeight:700}}>{fmt(computed.ig.clicks)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:computed.ig.ctr>2?P.mint:computed.ig.ctr>1?P.txt:P.warning,fontFamily:fm,fontSize:13,fontWeight:700}}>{pc(computed.ig.ctr)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:computed.ig.cpc<2?P.mint:P.txt,fontFamily:fm,fontSize:13,fontWeight:700}}>{fR(computed.ig.cpc)}</td></tr>
                <tr style={{background:"rgba(69,153,255,0.12)"}}><td style={{padding:"12px",border:"1px solid "+P.rule}}><span style={{fontSize:12,fontWeight:900,color:P.fb}}>Meta Total</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{fR(m.spend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{fmt(m.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{fmt(m.clicks)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{pc(m.ctr)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{fR(m.cpc)}</td></tr>
                <tr style={{background:"rgba(0,242,234,0.06)"}}><td style={{padding:"12px",border:"1px solid "+P.rule,display:"flex",alignItems:"center",gap:8}}><span style={{width:10,height:10,borderRadius:"50%",background:P.tt}}></span><span style={{fontSize:12,fontWeight:700,color:P.txt}}>TikTok</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13,fontWeight:700}}>{fR(t.spend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13}}>\\u2014</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13,fontWeight:700}}>{fmt(t.clicks)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13}}>\\u2014</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13}}>\\u2014</td></tr>
                <tr style={{background:"rgba(255,107,0,0.12)"}}><td style={{padding:"12px",border:"1px solid "+P.rule}}><span style={{fontSize:13,fontWeight:900,color:P.ember}}>GRAND TOTAL</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{fR(computed.totalSpend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{fmt(computed.grand.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{fmt(computed.totalClicks)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{pc(computed.grand.ctr)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{fR(computed.grand.cpc)}</td></tr>
              </tbody>
            </table>

            <div style={{background:"rgba(0,0,0,0.15)",borderRadius:12,padding:20,marginBottom:16}}><div style={{fontSize:10,fontWeight:800,color:P.sub,letterSpacing:3,fontFamily:fm,textTransform:"uppercase",marginBottom:14}}>Clicks & CPC by Platform</div><ResponsiveContainer width="100%" height={200}><BarChart data={[{name:"Facebook",Clicks:computed.fb.clicks,CPC:computed.fb.cpc},{name:"Instagram",Clicks:computed.ig.clicks,CPC:computed.ig.cpc},{name:"TikTok",Clicks:t.clicks,CPC:t.clicks>0?t.spend/t.clicks:0}]}><CartesianGrid strokeDasharray="3 3" stroke={P.rule}/><XAxis dataKey="name" tick={{fontSize:11,fill:P.txt,fontFamily:fm}} stroke="transparent"/><YAxis tick={{fontSize:10,fill:P.dim,fontFamily:fm}} stroke="transparent" tickFormatter={function(v){return fmt(v);}}/><Tooltip content={Tip}/><Bar dataKey="Clicks" fill={P.mint} radius={[6,6,0,0]} barSize={30}/></BarChart></ResponsiveContainer></div>

            <Insight title="Engagement Analysis" accent={P.mint} icon={Ic.pulse(P.mint,16)}>Facebook has generated <strong>{fmt(computed.fb.clicks)} clicks</strong> at <strong>{fR(computed.fb.cpc)} CPC</strong> with {pc(computed.fb.ctr)} CTR, confirming strong creative-audience alignment on the platform. Instagram contributed {fmt(computed.ig.clicks)} clicks at {fR(computed.ig.cpc)} CPC with {pc(computed.ig.ctr)} CTR. The combined Meta engagement of <strong>{fmt(m.clicks)} clicks</strong> at {fR(m.cpc)} blended CPC represents efficient conversion of awareness into measurable intent signals. TikTok contributed {fmt(t.clicks)} clicks through its performance network, with engagement metrics carrying additional amplification value as TikTok\\u2019s algorithm promotes content with strong interaction signals. {m.cpc<2?"Meta CPC below R2.00 is a positive efficiency signal \\u2014 consider scaling budget on top-performing ad sets.":m.cpc>5?"Meta CPC above R5.00 warrants creative review and potential audience refresh.":""}</Insight>
          </div>

          {/* \\u2550\\u2550\\u2550 OBJECTIVE ASSESSMENT \\u2550\\u2550\\u2550 */}
          <div style={{background:P.glass,borderRadius:18,padding:"6px 24px 24px",marginBottom:28,border:"1px solid "+P.rule}}>
            <div style={{textAlign:"center",padding:"18px 0 16px"}}><span style={{fontSize:18,fontWeight:900,color:P.txt,fontFamily:ff,letterSpacing:1}}>OBJECTIVE ASSESSMENT</span><div style={{fontSize:10,color:P.sub,fontFamily:fm,marginTop:4,letterSpacing:3}}>BOTTOM OF FUNNEL</div></div>

            {computed.grand.leads>0&&<div style={{marginBottom:20}}>
              <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:12}}><span style={{width:10,height:10,borderRadius:"50%",background:P.rose}}></span><span style={{fontSize:13,fontWeight:800,color:P.rose,fontFamily:ff}}>Lead Generation</span></div>
              <table style={{width:"100%",borderCollapse:"collapse",marginBottom:12}}>
                <thead><tr>{["","Media Spend","Reach","Clicks","Leads","Cost Per Lead"].map(function(h,i){return <th key={i} style={{padding:"10px 12px",fontSize:9,fontWeight:700,textTransform:"uppercase",color:"#FFCB05",textAlign:i===0?"left":"center",background:"#004F71",border:"1px solid #003a55",fontFamily:fm}}>{h}</th>;})}</tr></thead>
                <tbody>
                  <tr style={{background:"rgba(69,153,255,0.06)"}}><td style={{padding:"12px",border:"1px solid "+P.rule,display:"flex",alignItems:"center",gap:8}}><span style={{width:10,height:10,borderRadius:"50%",background:P.fb}}></span><span style={{fontSize:12,fontWeight:700,color:P.txt}}>Facebook</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13}}>{fR(computed.fb.spend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13}}>{fmt(computed.fb.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13}}>{fmt(computed.fb.clicks)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.mint,fontFamily:fm,fontSize:14,fontWeight:900}}>{fmt(computed.fb.leads)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:14,fontWeight:900}}>{computed.fb.leads>0?fR(computed.fb.costPerLead):"\\u2014"}</td></tr>
                  <tr style={{background:"rgba(225,48,108,0.06)"}}><td style={{padding:"12px",border:"1px solid "+P.rule,display:"flex",alignItems:"center",gap:8}}><span style={{width:10,height:10,borderRadius:"50%",background:P.ig}}></span><span style={{fontSize:12,fontWeight:700,color:P.txt}}>Instagram</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13}}>{fR(computed.ig.spend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13}}>{fmt(computed.ig.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13}}>{fmt(computed.ig.clicks)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.mint,fontFamily:fm,fontSize:14,fontWeight:900}}>{fmt(computed.ig.leads)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:14,fontWeight:900}}>{computed.ig.leads>0?fR(computed.ig.costPerLead):"\\u2014"}</td></tr>
                  <tr style={{background:"rgba(69,153,255,0.12)"}}><td style={{padding:"12px",border:"1px solid "+P.rule}}><span style={{fontSize:12,fontWeight:900,color:P.fb}}>Meta Total</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{fR(m.spend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{fmt(m.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{fmt(m.clicks)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.fb,fontFamily:fm,fontSize:15,fontWeight:900}}>{fmt(m.leads)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.fb,fontFamily:fm,fontSize:15,fontWeight:900}}>{m.leads>0?fR(m.costPerLead):"\\u2014"}</td></tr>
                  <tr style={{background:"rgba(255,107,0,0.12)"}}><td style={{padding:"12px",border:"1px solid "+P.rule}}><span style={{fontSize:13,fontWeight:900,color:P.ember}}>TOTAL</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{fR(computed.totalSpend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{fmt(computed.grand.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{fmt(computed.totalClicks)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:16,fontWeight:900}}>{fmt(computed.grand.leads)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:16,fontWeight:900}}>{computed.grand.leads>0?fR(computed.grand.costPerLead):"\\u2014"}</td></tr>
                </tbody>
              </table>
              <Insight title="Lead Generation Performance" accent={P.rose} icon={Ic.target(P.rose,16)}>The lead generation campaigns have delivered <strong>{fmt(computed.grand.leads)} leads</strong> at <strong>{computed.grand.leads>0?fR(computed.grand.spend/computed.grand.leads):"N/A"} cost per lead</strong>. Facebook contributed {fmt(computed.fb.leads)} leads at {computed.fb.leads>0?fR(computed.fb.costPerLead):"N/A"} CPL, whilst Instagram generated {fmt(computed.ig.leads)} leads at {computed.ig.leads>0?fR(computed.ig.costPerLead):"N/A"} CPL. {computed.fb.leads>0&&computed.ig.leads>0&&computed.ig.costPerLead<computed.fb.costPerLead?"Instagram is delivering leads more cost-efficiently than Facebook \\u2014 consider reallocating a portion of Facebook lead budget to Instagram to optimise blended CPL.":""}The quality of these leads should be validated against downstream conversion metrics to confirm they are translating into meaningful business outcomes.</Insight>
            </div>}

            {t.follows>0&&<div style={{marginBottom:20}}>
              <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:12}}><span style={{width:10,height:10,borderRadius:"50%",background:P.tt}}></span><span style={{fontSize:13,fontWeight:800,color:P.tt,fontFamily:ff}}>Community Growth (Follows)</span></div>
              <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:14}}>
                <Glass accent={P.tt} hv={true} st={{padding:20,textAlign:"center"}}><div style={{fontSize:9,color:P.dim,fontFamily:fm,letterSpacing:2,marginBottom:8}}>TT FOLLOWS</div><div style={{fontSize:28,fontWeight:900,color:P.mint,fontFamily:fm}}>{fmt(t.follows)}</div></Glass>
                <Glass accent={P.tt} hv={true} st={{padding:20,textAlign:"center"}}><div style={{fontSize:9,color:P.dim,fontFamily:fm,letterSpacing:2,marginBottom:8}}>COST PER FOLLOW</div><div style={{fontSize:28,fontWeight:900,color:P.tt,fontFamily:fm}}>{t.follows>0?fR(t.spend/t.follows):"\\u2014"}</div></Glass>
                <Glass accent={P.tt} hv={true} st={{padding:20,textAlign:"center"}}><div style={{fontSize:9,color:P.dim,fontFamily:fm,letterSpacing:2,marginBottom:8}}>TT LIKES</div><div style={{fontSize:28,fontWeight:900,color:P.fuchsia,fontFamily:fm}}>{fmt(t.likes)}</div></Glass>
              </div>
              <Insight title="Community Acquisition" accent={P.tt} icon={Ic.users(P.tt,16)}>TikTok has acquired <strong>{fmt(t.follows)} followers</strong> at {t.follows>0?fR(t.spend/t.follows):"N/A"} cost per follow, building a compounding organic asset that reduces future paid media dependency. Each follower increases organic content reach, provides a retargetable first-party audience, and signals brand affinity to TikTok\\u2019s recommendation engine. {t.likes>0?"The "+fmt(t.likes)+" engagements earned further amplify content distribution through TikTok\\u2019s algorithm, effectively delivering bonus organic impressions at zero marginal cost.":""}</Insight>
            </div>}

            {m.appInstalls>0&&<div style={{marginBottom:20}}>
              <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:12}}><span style={{width:10,height:10,borderRadius:"50%",background:P.fb}}></span><span style={{fontSize:13,fontWeight:800,color:P.fb,fontFamily:ff}}>App Install Clicks</span></div>
              <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:14}}>
                <Glass accent={P.fb} hv={true} st={{padding:20,textAlign:"center"}}><div style={{fontSize:9,color:P.dim,fontFamily:fm,letterSpacing:2,marginBottom:8}}>APP CLICKS</div><div style={{fontSize:28,fontWeight:900,color:P.fb,fontFamily:fm}}>{fmt(m.appInstalls)}</div></Glass>
                <Glass accent={P.fb} hv={true} st={{padding:20,textAlign:"center"}}><div style={{fontSize:9,color:P.dim,fontFamily:fm,letterSpacing:2,marginBottom:8}}>COST PER INSTALL</div><div style={{fontSize:28,fontWeight:900,color:P.ember,fontFamily:fm}}>{m.appInstalls>0?fR(m.costPerInstall):"\\u2014"}</div></Glass>
                <Glass accent={P.fb} hv={true} st={{padding:20,textAlign:"center"}}><div style={{fontSize:9,color:P.dim,fontFamily:fm,letterSpacing:2,marginBottom:8}}>TOTAL SPEND</div><div style={{fontSize:28,fontWeight:900,color:P.solar,fontFamily:fm}}>{fR(m.spend)}</div></Glass>
              </div>
            </div>}
          </div>

          {/* \\u2550\\u2550\\u2550 COMMUNITY GROWTH \\u2550\\u2550\\u2550 */}
          <div style={{background:P.glass,borderRadius:18,padding:"6px 24px 24px",marginBottom:28,border:"1px solid "+P.rule}}>
            <div style={{textAlign:"center",padding:"18px 0 16px"}}><span style={{fontSize:18,fontWeight:900,color:P.txt,fontFamily:ff,letterSpacing:1}}>COMMUNITY GROWTH</span><div style={{fontSize:10,color:P.sub,fontFamily:fm,marginTop:4,letterSpacing:3}}>PAGE LIKES & FOLLOWS BY PLATFORM</div></div>

            <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:16,marginBottom:20}}>
              <Glass accent={P.fb} hv={true} st={{padding:22,textAlign:"center"}}><div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:6,marginBottom:10}}><span style={{width:10,height:10,borderRadius:"50%",background:P.fb}}></span><span style={{fontSize:11,fontWeight:700,color:P.fb,fontFamily:fm}}>FACEBOOK</span></div><div style={{fontSize:9,color:P.dim,fontFamily:fm,letterSpacing:2,marginBottom:6}}>PAGE LIKES</div><div style={{fontSize:32,fontWeight:900,color:P.fb,fontFamily:fm}}>{fmt(m.pageLikes)}</div></Glass>
              <Glass accent={P.ig} hv={true} st={{padding:22,textAlign:"center"}}><div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:6,marginBottom:10}}><span style={{width:10,height:10,borderRadius:"50%",background:P.ig}}></span><span style={{fontSize:11,fontWeight:700,color:P.ig,fontFamily:fm}}>INSTAGRAM</span></div><div style={{fontSize:9,color:P.dim,fontFamily:fm,letterSpacing:2,marginBottom:6}}>FOLLOWERS</div><div style={{fontSize:32,fontWeight:900,color:P.ig,fontFamily:fm}}>{fmt(ig.pageLikes)}</div></Glass>
              <Glass accent={P.tt} hv={true} st={{padding:22,textAlign:"center"}}><div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:6,marginBottom:10}}><span style={{width:10,height:10,borderRadius:"50%",background:P.tt}}></span><span style={{fontSize:11,fontWeight:700,color:P.tt,fontFamily:fm}}>TIKTOK</span></div><div style={{fontSize:9,color:P.dim,fontFamily:fm,letterSpacing:2,marginBottom:6}}>FOLLOWS</div><div style={{fontSize:32,fontWeight:900,color:P.tt,fontFamily:fm}}>{fmt(t.follows)}</div></Glass>
            </div>

            <div style={{background:"rgba(0,0,0,0.15)",borderRadius:12,padding:20,marginBottom:16}}><div style={{fontSize:10,fontWeight:800,color:P.sub,letterSpacing:3,fontFamily:fm,textTransform:"uppercase",marginBottom:14}}>Community by Platform</div><ResponsiveContainer width="100%" height={200}><BarChart data={[{name:"FB Likes",value:m.pageLikes,fill:P.fb},{name:"IG Follows",value:ig.pageLikes,fill:P.ig},{name:"TT Follows",value:t.follows,fill:P.tt}]} barSize={40}><CartesianGrid strokeDasharray="3 3" stroke={P.rule}/><XAxis dataKey="name" tick={{fontSize:11,fill:P.txt,fontFamily:fm}} stroke="transparent"/><YAxis tick={{fontSize:10,fill:P.dim,fontFamily:fm}} stroke="transparent" tickFormatter={function(v){return fmt(v);}}/><Tooltip content={Tip}/><Bar dataKey="value" radius={[8,8,0,0]}><Cell fill={P.fb}/><Cell fill={P.ig}/><Cell fill={P.tt}/></Bar></BarChart></ResponsiveContainer></div>

            <Insight title="Community Value Assessment" accent={P.fuchsia} icon={Ic.users(P.fuchsia,16)}>The combined community growth of <strong>{fmt(m.pageLikes+ig.pageLikes+t.follows)} new members</strong> across Facebook ({fmt(m.pageLikes)} page likes), Instagram ({fmt(ig.pageLikes)} followers), and TikTok ({fmt(t.follows)} follows) represents a growing owned audience asset. Each community member reduces future paid media dependency by increasing organic content reach. Facebook page likes carry the highest organic reach weighting in Meta\\u2019s algorithm, Instagram followers drive Stories and Reels visibility, and TikTok follows feed directly into the For You page recommendation engine. This three-platform community strategy ensures brand presence across the dominant social ecosystems in South Africa.</Insight>
          </div>

        </div>)}

        """

    c = before + overview + after

    with open("/workspaces/media-on-gas/dashboard/src/App.jsx", "w") as f:
        f.write(c)
    print("Done - Overview tab rebuilt with funnel methodology")
    print("AWARENESS found:", "AWARENESS ASSESSMENT" in c)
    print("ENGAGEMENT found:", "ENGAGEMENT ASSESSMENT" in c)
    print("OBJECTIVE found:", "OBJECTIVE ASSESSMENT" in c)
    print("COMMUNITY found:", "COMMUNITY GROWTH" in c)
