import { useState, useEffect, useMemo } from "react";
import { BarChart, Bar, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";

var P={void:"#06020e",cosmos:"#0d0618",nebula:"#150b24",glass:"rgba(30,18,50,0.65)",ember:"#FF6B00",blaze:"#FF3D00",solar:"#FFAA00",lava:"#E8231A",orchid:"#A855F7",violet:"#7C3AED",fuchsia:"#D946EF",rose:"#F43F5E",cyan:"#22D3EE",mint:"#34D399",fb:"#4599FF",ig:"#E1306C",tt:"#00F2EA",txt:"#EDE9F5",sub:"#8B7FA3",dim:"#4A3D60",rule:"rgba(168,85,247,0.12)",critical:"#ef4444",warning:"#fbbf24",info:"#60a5fa",positive:"#4ade80"};
var gFire="linear-gradient(135deg,#E8231A,#FF6B00,#FFAA00)",gEmber="linear-gradient(135deg,#FF3D00,#FF6B00)";
var ff="Outfit,Segoe UI,sans-serif",fm="JetBrains Mono,Consolas,monospace";
var API=window.location.origin;
var LOOKER_URLS={"mtn momo pos":"https://lookerstudio.google.com/reporting/2c88c27a-4e0f-46ed-8ef9-afdb1b54a9dd/page/p_2upnicpx0d","momo pos":"https://lookerstudio.google.com/reporting/2c88c27a-4e0f-46ed-8ef9-afdb1b54a9dd/page/p_2upnicpx0d","momo":"https://lookerstudio.google.com/reporting/e527d821-db3b-4e60-9f3a-626165e2eed1/page/p_1ooj1p0nmd","mtn momo":"https://lookerstudio.google.com/reporting/e527d821-db3b-4e60-9f3a-626165e2eed1/page/p_1ooj1p0nmd","willowbrook":"https://lookerstudio.google.com/reporting/823fd5fa-b39d-4dc3-b623-549197d0341f/page/p_2upnicpx0d","psycho":"https://lookerstudio.google.com/reporting/0adc106a-50e2-42cc-a4ca-aafc04160e5d/page/p_1ooj1p0nmd","khava":"","concord":"","eden":"","flower":""};
var LOOKER_KEYS=["mtn momo pos","momo pos","willowbrook","psycho","khava","concord","eden","flower","momo","mtn momo"];
function findLookerUrl(camps,sel){var s=camps.filter(function(x){return sel.indexOf(x.campaignId)>=0;});if(s.length===0)return{url:"",client:"none"};var names=s.map(function(x){return(x.campaignName||"").toLowerCase();}).join(" ");for(var i=0;i<LOOKER_KEYS.length;i++){if(names.indexOf(LOOKER_KEYS[i])>=0){var u=LOOKER_URLS[LOOKER_KEYS[i]];return{url:u,client:LOOKER_KEYS[i]};}}return{url:"",client:"unknown"};}
var fmt=function(n){var v=parseFloat(n);if(isNaN(v))return"0";if(v>=1e6)return(v/1e6).toFixed(2)+"M";if(v>=1e3)return(v/1e3).toFixed(1)+"K";return Math.round(v).toLocaleString();};
var fR=function(n){var v=parseFloat(n);return isNaN(v)?"R0.00":"R"+v.toLocaleString("en-ZA",{minimumFractionDigits:2,maximumFractionDigits:2});};
var pc=function(n){var v=parseFloat(n);return isNaN(v)?"0.00%":v.toFixed(2)+"%";};

var Ic={
chart:function(c,s){s=s||20;return<svg width={s} height={s} viewBox="0 0 24 24" fill="none"><rect x="3" y="12" width="4" height="9" rx="1" stroke={c} strokeWidth="1.5" fill={c+"15"}/><rect x="10" y="6" width="4" height="15" rx="1" stroke={c} strokeWidth="1.5" fill={c+"15"}/><rect x="17" y="2" width="4" height="19" rx="1" stroke={c} strokeWidth="1.5" fill={c+"15"}/></svg>;},
radar:function(c,s){s=s||20;return<svg width={s} height={s} viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="10" stroke={c} strokeWidth="1.5" opacity="0.3"/><circle cx="12" cy="12" r="6" stroke={c} strokeWidth="1.5" opacity="0.5"/><circle cx="12" cy="12" r="2" fill={c}/></svg>;},
pulse:function(c,s){s=s||20;return<svg width={s} height={s} viewBox="0 0 24 24" fill="none"><path d="M2 12h4l3-8 4 16 3-8h6" stroke={c} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>;},
target:function(c,s){s=s||20;return<svg width={s} height={s} viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="10" stroke={c} strokeWidth="1.5"/><circle cx="12" cy="12" r="6" stroke={c} strokeWidth="1.5"/><circle cx="12" cy="12" r="2" fill={c}/></svg>;},
bolt:function(c,s){s=s||20;return<svg width={s} height={s} viewBox="0 0 24 24" fill="none"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z" stroke={c} strokeWidth="1.5" fill={c+"15"} strokeLinejoin="round"/></svg>;},
eye:function(c,s){s=s||20;return<svg width={s} height={s} viewBox="0 0 24 24" fill="none"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8S1 12 1 12z" stroke={c} strokeWidth="1.5"/><circle cx="12" cy="12" r="3" stroke={c} strokeWidth="1.5"/></svg>;},
crown:function(c,s){s=s||20;return<svg width={s} height={s} viewBox="0 0 24 24" fill="none"><path d="M2 20h20L19 8l-4 5-3-7-3 7-4-5L2 20z" stroke={c} strokeWidth="1.5" fill={c+"15"} strokeLinejoin="round"/></svg>;},
users:function(c,s){s=s||20;return<svg width={s} height={s} viewBox="0 0 24 24" fill="none"><circle cx="9" cy="7" r="3" stroke={c} strokeWidth="1.5"/><path d="M2 21v-2a5 5 0 0110 0v2" stroke={c} strokeWidth="1.5"/></svg>;},
globe:function(c,s){s=s||20;return<svg width={s} height={s} viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="10" stroke={c} strokeWidth="1.5"/><path d="M2 12h20" stroke={c} strokeWidth="1" opacity="0.3"/></svg>;},
share:function(c,s){s=s||20;return<svg width={s} height={s} viewBox="0 0 24 24" fill="none"><circle cx="18" cy="5" r="3" stroke={c} strokeWidth="1.5"/><circle cx="6" cy="12" r="3" stroke={c} strokeWidth="1.5"/><circle cx="18" cy="19" r="3" stroke={c} strokeWidth="1.5"/><line x1="8.59" y1="13.51" x2="15.42" y2="17.49" stroke={c} strokeWidth="1.5"/><line x1="15.41" y1="6.51" x2="8.59" y2="10.49" stroke={c} strokeWidth="1.5"/></svg>;},
check:function(c,s){s=s||20;return<svg width={s} height={s} viewBox="0 0 24 24" fill="none"><path d="M20 6L9 17l-5-5" stroke={c} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>;},
flag:function(c,s){s=s||20;return<svg width={s} height={s} viewBox="0 0 24 24" fill="none"><path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" stroke={c} strokeWidth="1.5" fill={c+"15"}/><line x1="4" y1="22" x2="4" y2="15" stroke={c} strokeWidth="1.5"/></svg>;},
alert:function(c,s){s=s||20;return<svg width={s} height={s} viewBox="0 0 24 24" fill="none"><path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z" stroke={c} strokeWidth="1.5"/><line x1="12" y1="9" x2="12" y2="13" stroke={c} strokeWidth="1.5"/></svg>;},
fire:function(c,s){s=s||20;return<svg width={s} height={s} viewBox="0 0 24 24" fill="none"><path d="M12 2c0 4-4 6-4 10a6 6 0 0012 0c0-4-4-6-4-10z" stroke={c} strokeWidth="1.5" fill={c+"20"}/></svg>;}
};

function Glass(props){var a=props.accent||P.ember,st=props.st||{},hv=props.hv;var s=useState(false);return(<div onMouseEnter={function(){s[1](true);}} onMouseLeave={function(){s[1](false);}} style={Object.assign({background:P.glass,border:"1px solid "+(s[0]&&hv?a+"50":P.rule),borderRadius:16,position:"relative",overflow:"hidden",transition:"all 0.3s ease",transform:s[0]&&hv?"translateY(-2px)":"none",boxShadow:s[0]&&hv?"0 12px 40px "+a+"15":"0 4px 20px rgba(0,0,0,0.25)"},st)}><div style={{position:"absolute",top:0,left:"10%",right:"10%",height:1,background:"linear-gradient(90deg,transparent,"+a+"80,transparent)",opacity:s[0]&&hv?1:0.4}}/>{props.children}</div>);}
function Metric(props){return(<Glass accent={props.accent} hv={true} st={{padding:"22px 20px"}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:14}}><div style={{display:"flex",alignItems:"center",gap:8}}>{props.icon}<span style={{fontSize:9,fontWeight:700,color:P.sub,letterSpacing:2.5,textTransform:"uppercase",fontFamily:fm}}>{props.label}</span></div><div style={{width:8,height:8,borderRadius:"50%",background:props.accent,boxShadow:"0 0 12px "+props.accent+"60",animation:"pulse-glow 2s ease-in-out infinite"}}></div></div><div style={{fontSize:28,fontWeight:900,fontFamily:ff,lineHeight:1,letterSpacing:-1.5,color:props.accent,marginBottom:6}}>{props.value}</div>{props.sub&&<div style={{fontSize:10,color:P.dim,marginTop:10,fontFamily:fm,lineHeight:1.7,borderTop:"1px solid "+P.rule,paddingTop:10}}>{props.sub}</div>}</Glass>);}
function SH(props){var a=props.accent||P.ember;return(<div style={{marginBottom:28}}><div style={{display:"flex",alignItems:"center",gap:14}}><div style={{width:40,height:40,borderRadius:12,background:"linear-gradient(135deg,"+a+"20,"+a+"08)",border:"1px solid "+a+"30",display:"flex",alignItems:"center",justifyContent:"center"}}>{props.icon}</div><div><h2 style={{margin:0,fontSize:22,fontWeight:900,color:P.txt,fontFamily:ff}}>{props.title}</h2>{props.sub&&<p style={{margin:"2px 0 0",fontSize:11,color:P.sub,fontFamily:fm}}>{props.sub}</p>}</div></div><div style={{height:1,marginTop:16,background:"linear-gradient(90deg,"+a+"50,"+a+"15,transparent 80%)"}}/></div>);}
function Pill(props){return(<span style={{display:"inline-flex",alignItems:"center",gap:5,background:props.color+"12",border:"1px solid "+props.color+"30",borderRadius:20,padding:"3px 10px",fontSize:9,fontWeight:700,color:props.color,fontFamily:fm,textTransform:"uppercase"}}><span style={{width:6,height:6,borderRadius:"50%",background:props.color}}/>{props.name}</span>);}
function Tip(props){if(!props.active||!props.payload||!props.payload.length)return null;return(<div style={{background:"rgba(22,12,38,0.95)",border:"1px solid "+P.rule,borderRadius:12,padding:"10px 14px"}}><div style={{fontSize:11,fontWeight:800,color:P.txt,fontFamily:fm,marginBottom:4}}>{props.label}</div>{props.payload.map(function(p,i){return<div key={i} style={{fontSize:11,color:p.color||P.sub,fontFamily:fm,lineHeight:1.8}}>{p.name}: {typeof p.value==="number"?p.value.toLocaleString():p.value}</div>;})}</div>);}
function PH(props){var bg=props.platform==="Facebook"?P.fb:props.platform==="Instagram"?"linear-gradient(135deg,#e1306c,#833ab4)":props.platform==="TikTok"?"#1e1e2e":P.ember;var dot=props.platform==="Facebook"?"#fff":props.platform==="TikTok"?P.tt:"#fff";return(<div style={{background:bg,padding:"14px 24px",borderRadius:12,marginBottom:18,display:"flex",alignItems:"center",justifyContent:"space-between",boxShadow:"0 4px 20px rgba(0,0,0,0.3)"}}><div style={{display:"flex",alignItems:"center",gap:10}}><span style={{width:10,height:10,borderRadius:"50%",background:dot,boxShadow:"0 0 10px "+dot}}></span><span style={{fontSize:15,fontWeight:800,color:"#fff",fontFamily:ff,letterSpacing:0.5}}>{props.platform}</span>{props.suffix&&<span style={{fontSize:12,fontWeight:400,color:"rgba(255,255,255,0.6)",fontFamily:fm}}>· {props.suffix}</span>}</div><div style={{fontSize:10,fontWeight:700,color:"rgba(255,255,255,0.4)",fontFamily:fm,letterSpacing:2,textTransform:"uppercase"}}>LIVE DATA</div></div>);}
function Insight(props){var a=props.accent||P.ember;return(<div style={{marginTop:24,padding:"22px 26px",background:"linear-gradient(135deg,"+a+"08 0%,"+a+"03 50%, transparent 100%)",border:"1px solid "+a+"20",borderLeft:"4px solid "+a,borderRadius:"0 14px 14px 0",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",top:0,left:4,width:120,height:"100%",background:"linear-gradient(90deg,"+a+"06, transparent)",pointerEvents:"none"}}></div><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:14,position:"relative"}}>{props.icon||Ic.bolt(a,16)}<span style={{fontSize:10,fontWeight:800,color:a,letterSpacing:3,fontFamily:fm,textTransform:"uppercase"}}>{props.title||"Campaign Read"}</span><div style={{flex:1,height:1,background:"linear-gradient(90deg,"+a+"30, transparent)",marginLeft:8}}></div></div><div style={{fontSize:13.5,color:P.txt,lineHeight:2.1,fontFamily:ff,position:"relative",letterSpacing:0.2}}>{props.children}</div></div>);}
function SevBadge(props){var c={critical:P.critical,warning:P.warning,info:P.info,positive:P.positive}[props.s]||P.info;return(<span style={{display:"inline-flex",alignItems:"center",gap:5,background:c+"18",border:"1px solid "+c+"40",borderRadius:6,padding:"3px 10px",fontSize:10,fontWeight:800,color:c,fontFamily:fm,textTransform:"uppercase"}}><span style={{width:7,height:7,borderRadius:"50%",background:c}}/>{props.s}</span>);}

function CampaignSelector(props){
  var cs=props.campaigns,sel=props.selected,search=props.search;
  var f=cs.filter(function(c){return c.campaignName.toLowerCase().indexOf(search.toLowerCase())>=0||c.accountName.toLowerCase().indexOf(search.toLowerCase())>=0;});
  var g={};f.forEach(function(c){var k=c.platform+"—"+c.accountName;if(!g[k])g[k]={platform:c.platform,campaigns:[]};g[k].campaigns.push(c);});
  return(<div style={{background:P.glass,border:"1px solid "+P.rule,borderRadius:16,padding:18,maxHeight:480,overflowY:"auto"}}>
    <input placeholder="Search campaigns..." value={search} onChange={function(e){props.onSearch(e.target.value);}} style={{width:"100%",boxSizing:"border-box",background:"rgba(40,25,60,0.5)",border:"1px solid "+P.rule,borderRadius:8,padding:"8px 14px",color:P.txt,fontSize:12,fontFamily:fm,outline:"none",marginBottom:12}}/>
    <div style={{display:"flex",gap:8,marginBottom:12}}>
      <button onClick={props.onSelectAll} style={{background:P.ember+"15",border:"1px solid "+P.ember+"30",borderRadius:8,padding:"4px 12px",color:P.ember,fontSize:10,fontWeight:700,fontFamily:fm,cursor:"pointer"}}>All ({f.length})</button>
      <button onClick={props.onClearAll} style={{background:P.rule,border:"1px solid "+P.rule,borderRadius:8,padding:"4px 12px",color:P.sub,fontSize:10,fontWeight:700,fontFamily:fm,cursor:"pointer"}}>Clear</button>
      <span style={{fontSize:10,color:P.dim,fontFamily:fm,alignSelf:"center",marginLeft:"auto"}}>{sel.length} sel</span>
    </div>
    {Object.keys(g).map(function(k){var gr=g[k];var gc=gr.platform==="TikTok"?P.tt:P.fb;return(<div key={k} style={{marginBottom:12}}><div style={{display:"flex",alignItems:"center",gap:6,marginBottom:6,paddingBottom:4,borderBottom:"1px solid "+P.rule}}><span style={{width:7,height:7,borderRadius:"50%",background:gc}}/><span style={{fontSize:9,fontWeight:800,color:gc,letterSpacing:2,textTransform:"uppercase",fontFamily:fm}}>{k}</span></div>
      {gr.campaigns.map(function(c){var s=sel.indexOf(c.campaignId)>=0;return(<div key={c.campaignId} onClick={function(){props.onToggle(c.campaignId);}} style={{display:"flex",alignItems:"center",gap:8,padding:"6px 10px",marginBottom:2,borderRadius:8,cursor:"pointer",background:s?gc+"10":"transparent",border:"1px solid "+(s?gc+"30":"transparent")}}>
        <div style={{width:18,height:18,borderRadius:5,border:"2px solid "+(s?gc:P.dim),background:s?gc:"transparent",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}>{s&&Ic.check("#fff",12)}</div>
        <div style={{flex:1,minWidth:0}}><div title={c.campaignName} style={{fontSize:11,fontWeight:600,color:s?P.txt:P.sub,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis",cursor:"help"}}>{c.campaignName}</div><div style={{fontSize:9,color:P.dim,fontFamily:fm}}>{fmt(c.impressions)} imps {c.status&&c.status!=="active"&&<span style={{color:c.status==="scheduled"?P.solar:c.status==="pending"?P.cyan:c.status==="completed"?P.sub:P.warning,fontWeight:700,textTransform:"uppercase",marginLeft:4}}>{c.status}</span>} · {fR(parseFloat(c.spend))}</div></div>
      </div>);})}
    </div>);})}
  </div>);
}

function ShareModal(props){var cs=useState(false);var copy=function(){navigator.clipboard.writeText(window.location.href);cs[1](true);setTimeout(function(){cs[1](false);},2000);};return(<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.7)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:1000}} onClick={props.onClose}><div onClick={function(e){e.stopPropagation();}} style={{background:P.cosmos,border:"1px solid "+P.rule,borderRadius:20,padding:32,width:480,maxWidth:"90vw"}}><div style={{fontSize:18,fontWeight:900,color:P.txt,fontFamily:ff,marginBottom:6}}>Share with Client</div><div style={{fontSize:12,color:P.sub,marginBottom:16}}>Client gets read-only access with date toggles. No campaign selector, no optimisation tab.</div><div style={{display:"flex",gap:8}}><input readOnly value={window.location.href} style={{flex:1,background:P.glass,border:"1px solid "+P.rule,borderRadius:10,padding:"10px 14px",color:P.txt,fontSize:12,fontFamily:fm,outline:"none"}}/><button onClick={copy} style={{background:cs[0]?P.mint:gEmber,border:"none",borderRadius:10,padding:"10px 20px",color:"#fff",fontSize:12,fontWeight:800,fontFamily:fm,cursor:"pointer"}}>{cs[0]?"Copied!":"Copy"}</button></div></div></div>);}

function genFlags(m,t,camps){
  var fl=[],id=1;
  var metaImpShare=m.impressions>0&&t.impressions>0?(m.impressions/(m.impressions+t.impressions)*100):0;
  var ttImpShare=t.impressions>0&&m.impressions>0?(t.impressions/(m.impressions+t.impressions)*100):0;
  var metaSpendShare=m.spend>0&&t.spend>0?(m.spend/(m.spend+t.spend)*100):0;
  var blendedCpc=(m.clicks+t.clicks)>0?(m.spend+t.spend)/(m.clicks+t.clicks):0;
  var cpfTT=t.follows>0?t.spend/t.follows:0;
  if(m.frequency>4.0)fl.push({id:id++,severity:"critical",platform:"Meta",metric:"Audience Saturation — Frequency",currentValue:m.frequency.toFixed(2)+"x",threshold:"4.0x",message:"Meta frequency has breached the critical 4.0x ceiling. At this level, diminishing returns accelerate sharply — each additional impression delivers progressively less incremental value whilst actively increasing the risk of negative brand sentiment and audience fatigue. Historical benchmarks show engagement rates typically decline 15-25% once frequency exceeds 4x in a single flight.",recommendation:"Immediately implement audience exclusion rules for users with 4+ impressions. Rotate in fresh creative assets to reset engagement curves. Consider splitting the budget across a broader Lookalike stack (1-3%, 3-5%, 5-10%) to access untapped reach pools whilst maintaining quality.",status:"open"});
  else if(m.frequency>3.0)fl.push({id:id++,severity:"warning",platform:"Meta",metric:"Frequency Pressure Building",currentValue:m.frequency.toFixed(2)+"x",threshold:"3.0x",message:"Meta frequency is approaching the fatigue threshold at "+m.frequency.toFixed(2)+"x. Whilst still within acceptable range for direct-response campaigns, sustained delivery at this level will erode CTR and inflate CPC within the next 3-5 days if audience pools are not refreshed.",recommendation:"Proactively expand audience size by layering in new interest-based or behavioural targeting segments. Schedule a creative rotation for the next 48 hours — even minor variations (colour shifts, headline swaps, thumbnail changes) can reset the frequency curve and extend the productive lifespan of the ad set.",status:"open"});
  if(m.ctr>0&&m.ctr<0.8)fl.push({id:id++,severity:"critical",platform:"Meta",metric:"Engagement Deficit — CTR",currentValue:pc(m.ctr),threshold:"0.80%",message:"Meta CTR at "+pc(m.ctr)+" is significantly below the 0.80% floor for paid social in the South African market. This indicates a fundamental disconnect between the creative message and the target audience — the ads are being served but failing to generate meaningful intent signals. Low CTR also degrades Meta’s quality ranking, which compounds the problem by increasing CPM.",recommendation:"Conduct an immediate creative audit: review thumb-stop rates (are users pausing?), hook completion rates (are they watching past 3 seconds?), and CTA click-through. Test UGC-style creative against polished brand assets — UGC typically outperforms by 30-50% on CTR in the ZA market. Verify audience-message alignment: are you showing data deals to data-hungry segments, or mismatching offers?",status:"open"});
  else if(m.ctr>0&&m.ctr<1.2)fl.push({id:id++,severity:"warning",platform:"Meta",metric:"CTR Below Benchmark",currentValue:pc(m.ctr),threshold:"1.20%",message:"Meta CTR at "+pc(m.ctr)+" is below the 1.20% benchmark for optimised paid social campaigns. Whilst not critical, this suggests room for creative or targeting refinement that could materially improve downstream conversion efficiency.",recommendation:"A/B test three creative variations: (1) different opening hooks in the first 2 seconds, (2) stronger value proposition in the primary text, (3) more urgent or specific CTA copy. Also test narrowing the audience to higher-intent segments — a smaller but more engaged audience often delivers better blended ROI than broad reach with weak engagement.",status:"open"});
  if(m.cpc>0&&m.cpc>5.0)fl.push({id:id++,severity:"critical",platform:"Meta",metric:"Cost Efficiency Alert — CPC",currentValue:fR(m.cpc),threshold:"R5.00",message:"Meta CPC at "+fR(m.cpc)+" has exceeded the R5.00 efficiency ceiling. At this rate, the cost to drive each click is eroding campaign ROI and suggests either creative fatigue, audience saturation, or competitive auction pressure in the targeted segments.",recommendation:"Shift budget allocation toward your lowest-CPC ad sets immediately. Pause any ad sets with CPC above "+fR(m.cpc*1.2)+" and reallocate to proven performers. Test Advantage+ placements to access lower-cost inventory across Reels, Stories, and the Audience Network. Consider bid cap strategies to enforce CPC discipline.",status:"open"});
  if(t.cpm>0&&m.cpm>0){var cpmRatio=m.cpm/t.cpm;if(cpmRatio>3.0)fl.push({id:id++,severity:"warning",platform:"Cross-platform",metric:"Platform Efficiency Gap — CPM",currentValue:cpmRatio.toFixed(1)+"x differential",threshold:"3.0x",message:"Meta is delivering impressions at "+fR(m.cpm)+" CPM versus TikTok’s "+fR(t.cpm)+" CPM — a "+cpmRatio.toFixed(1)+"x cost differential. Whilst Meta’s higher CPM reflects richer targeting data and stronger attribution, a gap this wide warrants strategic budget rebalancing to optimise overall campaign efficiency.",recommendation:"Model a 10-15% budget shift from Meta awareness campaigns to TikTok, maintaining Meta’s allocation for conversion and retargeting objectives where its attribution advantage justifies the premium. Run a two-week test comparing blended CPA across both allocation models before committing to a permanent shift."});
  else if(cpmRatio>2.0)fl.push({id:id++,severity:"info",platform:"Cross-platform",metric:"CPM Variance Across Platforms",currentValue:cpmRatio.toFixed(1)+"x differential",threshold:"2.0x",message:"Meta CPM ("+fR(m.cpm)+") runs "+cpmRatio.toFixed(1)+"x higher than TikTok ("+fR(t.cpm)+"). This is within normal range for a dual-platform strategy where Meta handles precision targeting and TikTok drives scale, but worth monitoring as the gap widens.",recommendation:"Continue monitoring the CPM delta weekly. If it exceeds 3x, evaluate whether Meta’s higher-funnel campaigns (awareness, reach) could be more efficiently served on TikTok, reserving Meta budget for mid-to-lower funnel objectives where its measurement stack provides clearer ROI visibility.",status:"open"});}
  if(metaSpendShare>75&&ttImpShare>50)fl.push({id:id++,severity:"info",platform:"Cross-platform",metric:"Budget-to-Impression Imbalance",currentValue:metaSpendShare.toFixed(0)+"% spend on Meta",threshold:"75%",message:"Meta is consuming "+metaSpendShare.toFixed(0)+"% of budget but TikTok is delivering "+ttImpShare.toFixed(0)+"% of impressions. This suggests TikTok is significantly more capital-efficient for reach, and the current allocation may be over-indexing on Meta for awareness objectives.",recommendation:"Review whether Meta’s outsized budget share is justified by conversion performance. If Meta is driving the majority of measurable conversions, the allocation is correct. If both platforms serve primarily awareness objectives, rebalance toward TikTok’s superior impression economics.",status:"open"});
  if(m.cpc>0&&m.cpc<1.50)fl.push({id:id++,severity:"positive",platform:"Meta",metric:"Strong Click Efficiency",currentValue:fR(m.cpc),threshold:"R1.50",message:"Meta CPC at "+fR(m.cpc)+" is operating well below the R1.50 efficiency benchmark for South African paid social. This indicates excellent creative-audience fit — the algorithm has identified high-intent audience pockets and the creative is converting attention into action at an efficient rate.",recommendation:"This is a scale signal. Increase daily budgets by 15-20% on the top-performing ad sets to capitalise on the efficient delivery window before auction dynamics shift. Document the winning creative elements (hook, format, CTA) for replication across future campaigns.",status:"open"});
  else if(m.cpc>0&&m.cpc<3.0)fl.push({id:id++,severity:"positive",platform:"Meta",metric:"CPC Within Target Range",currentValue:fR(m.cpc),threshold:"R3.00",message:"Meta CPC at "+fR(m.cpc)+" is within the healthy R1.50-R3.00 range for direct-response campaigns in the SA market, confirming effective creative and audience targeting.",recommendation:"Maintain current optimisation approach. Focus on incremental improvements: test new ad formats (Reels, carousel) against current winners, and expand Lookalike audiences from 1% to 2-3% to increase addressable reach without sacrificing click quality.",status:"open"});
  if(t.follows>1000){var cpf=t.spend/t.follows;fl.push({id:id++,severity:"positive",platform:"TikTok",metric:"Community Acquisition Momentum",currentValue:fmt(t.follows)+" follows at "+fR(cpf)+" CPF",threshold:"1,000 follows",message:"TikTok has acquired "+fmt(t.follows)+" followers at "+fR(cpf)+" cost-per-follow. This community represents a compounding organic asset — each follower increases future organic reach, reduces paid media dependency, and provides a retargetable first-party audience for subsequent campaigns.",recommendation:"Accelerate community investment. The current CPF of "+fR(cpf)+" is below market rates for quality follower acquisition. Consider allocating an additional 10-15% of TikTok budget specifically to follower campaigns whilst the creative is resonating. Every follower acquired now reduces future paid reach costs.",status:"open"});}
  else if(t.follows>200)fl.push({id:id++,severity:"positive",platform:"TikTok",metric:"Community Growth Active",currentValue:fmt(t.follows)+" follows",threshold:"200",message:"TikTok follower acquisition is tracking positively with "+fmt(t.follows)+" new follows in the period. Building owned audience on TikTok reduces long-term paid media dependency.",recommendation:"Continue current follower strategy. Test creator-led content and trending audio formats to accelerate organic follow rates alongside paid acquisition.",status:"open"});
  if(t.cpm>0&&t.cpm<8)fl.push({id:id++,severity:"positive",platform:"TikTok",metric:"Exceptional Impression Value",currentValue:fR(t.cpm)+" CPM",threshold:"R8.00",message:"TikTok is delivering impressions at "+fR(t.cpm)+" CPM — significantly below the R8.00 benchmark for the South African market. At this rate, every R1,000 buys approximately "+fmt(Math.round(1000/t.cpm*1000))+" impressions, making TikTok the most capital-efficient awareness channel in the campaign.",recommendation:"Maximise TikTok as the primary scale and awareness channel. This CPM level typically indicates strong content relevance scores and favourable auction positioning — the algorithm is rewarding the creative quality. Increase investment to capture this efficiency window before competitive pressure normalises rates.",status:"open"});
  else if(t.cpm>0&&t.cpm<15)fl.push({id:id++,severity:"positive",platform:"TikTok",metric:"Competitive CPM",currentValue:fR(t.cpm)+" CPM",threshold:"R15.00",message:"TikTok CPM at "+fR(t.cpm)+" is within the efficient range for paid social in South Africa, confirming good content-audience alignment.",recommendation:"Monitor CPM trends weekly. If CPM begins rising above R15, review creative freshness and audience targeting for signs of saturation.",status:"open"});
  camps.filter(function(c){return parseFloat(c.spend)>3000;}).forEach(function(c){
    var cCtr=parseFloat(c.ctr||0);var cCpc=parseFloat(c.cpc||0);var cSpend=parseFloat(c.spend);var cImps=parseFloat(c.impressions||0);
    if(cCtr<0.6&&cImps>10000)fl.push({id:id++,severity:"critical",platform:c.platform||"Meta",metric:"Underperforming Campaign",currentValue:pc(cCtr)+" CTR on "+fR(cSpend),threshold:"0.60% CTR",message:"Campaign ‘"+c.campaignName+"’ is delivering "+pc(cCtr)+" CTR with "+fR(cSpend)+" invested against "+fmt(cImps)+" impressions. This level of engagement failure with meaningful spend indicates a structural issue with either creative relevance, audience targeting, or landing page experience.",recommendation:"Conduct a three-part diagnostic: (1) Creative — are the first 3 seconds compelling enough to stop the scroll? (2) Audience — is the targeting aligned with the offer? (3) Landing page — does the destination match the ad promise? Pause the lowest-performing ad sets and reallocate budget to campaigns delivering above "+pc(1.0)+" CTR.",status:"open"});
    else if(cCtr<1.0&&cImps>5000)fl.push({id:id++,severity:"warning",platform:c.platform||"Meta",metric:"Below-Benchmark Campaign",currentValue:pc(cCtr)+" CTR",threshold:"1.00%",message:"Campaign ‘"+c.campaignName+"’ at "+pc(cCtr)+" CTR is underperforming against the 1.0% benchmark with "+fR(cSpend)+" spend.",recommendation:"Review the top 3 ad creatives within this campaign. Replace the lowest performer with a new variant testing a different hook, format, or value proposition.",status:"open"});
    if(cCpc>8&&c.platform==="Meta")fl.push({id:id++,severity:"warning",platform:"Meta",metric:"High CPC Campaign",currentValue:fR(cCpc)+" CPC",threshold:"R8.00",message:"Campaign ‘"+c.campaignName+"’ is running at "+fR(cCpc)+" CPC, well above the efficient range. This inflated cost-per-click is dragging down the blended account CPC.",recommendation:"Review the bid strategy on this campaign. Switch from lowest-cost to cost-cap bidding with a target CPC of "+fR(cCpc*0.6)+". If performance doesn’t improve within 48 hours, consolidate this campaign’s budget into higher-performing campaigns.",status:"open"});
  });
  if(blendedCpc>0&&blendedCpc<2.0)fl.push({id:id++,severity:"positive",platform:"Cross-platform",metric:"Blended Cost Efficiency",currentValue:fR(blendedCpc)+" blended CPC",threshold:"R2.00",message:"The cross-platform blended CPC of "+fR(blendedCpc)+" confirms the multi-channel strategy is delivering cost-efficient engagement. The combination of Meta’s targeted clicks and TikTok’s volume-driven engagement is optimising the overall cost base.",recommendation:"This efficiency level supports budget scaling. Model a 15-20% budget increase across both platforms and monitor whether the blended CPC holds below R2.00 — if it does, the campaign has room to grow without sacrificing efficiency.",status:"open"});
  fl.sort(function(a,b){var o={critical:0,warning:1,info:2,positive:3};return(o[a.severity]||9)-(o[b.severity]||9);});
  return fl;
}

export default function MediaOnGas(){
  var ts=useState("overview"),tab=ts[0],setTab=ts[1];
  var ds=useState("2026-04-01"),df=ds[0],setDf=ds[1];
  var de=useState("2026-04-07"),dt=de[0],setDt=de[1];
  var cs=useState([]),campaigns=cs[0],setCampaigns=cs[1];
  var ss=useState([]),selected=ss[0],setSelected=ss[1];
  var rs=useState(""),search=rs[0],setSearch=rs[1];
  var ls=useState(true),loading=ls[0],setLoading=ls[1];
  var sc=useState(false),showCampaigns=sc[0],setShowCampaigns=sc[1];
  var sm=useState(false),showShare=sm[0],setShowShare=sm[1];
  var fs=useState([]),flags=fs[0],setFlags=fs[1];
  var isClient=window.location.pathname.indexOf("/view/")===0;

  var fetchData=function(){setLoading(true);fetch(API+"/api/campaigns?from="+df+"&to="+dt).then(function(r){return r.json();}).then(function(d){if(d.campaigns){setCampaigns(d.campaigns);setSelected(d.campaigns.map(function(c){return c.campaignId;}));}setLoading(false);}).catch(function(){setLoading(false);});};
  useEffect(function(){fetchData();},[]);
  var refreshData=function(){fetchData();};
  var toggle=function(id){setSelected(function(p){return p.indexOf(id)>=0?p.filter(function(x){return x!==id;}):p.concat([id]);});};
  var selectAll=function(){var f=campaigns.filter(function(c){return c.campaignName.toLowerCase().indexOf(search.toLowerCase())>=0||c.accountName.toLowerCase().indexOf(search.toLowerCase())>=0;});setSelected(f.map(function(c){return c.campaignId;}));};
  var clearAll=function(){setSelected([]);};

  var computed=useMemo(function(){
    if(selected.length===0)return{metaCamps:[],ttCamps:[],meta:{impressions:0,reach:0,spend:0,clicks:0,cpm:0,cpc:0,ctr:0,frequency:0},tt:{impressions:0,spend:0,clicks:0,follows:0,likes:0,cpm:0},totalImps:0,totalSpend:0,totalClicks:0,blendedCpm:0,allSelected:[]};
    var sel=campaigns.filter(function(c){return selected.indexOf(c.campaignId)>=0;});
    var fbC=sel.filter(function(c){return c.platform==="Facebook";});
    var igC=sel.filter(function(c){return c.platform==="Instagram";});
    var mc=sel.filter(function(c){return c.platform==="Facebook"||c.platform==="Instagram"||c.platform==="Meta";});
    var tc=sel.filter(function(c){return c.platform==="TikTok";});
    var sumP=function(arr){return arr.reduce(function(a,c){return{impressions:a.impressions+parseFloat(c.impressions||0),reach:a.reach+parseFloat(c.reach||0),spend:a.spend+parseFloat(c.spend||0),clicks:a.clicks+parseFloat(c.clicks||0),leads:a.leads+parseFloat(c.leads||0),appInstalls:a.appInstalls+parseFloat(c.appInstalls||0),landingPageViews:a.landingPageViews+parseFloat(c.landingPageViews||0),pageLikes:a.pageLikes+parseFloat(c.pageLikes||0),follows:a.follows+parseFloat(c.follows||0),likes:a.likes+parseFloat(c.likes||0)};},{impressions:0,reach:0,spend:0,clicks:0,leads:0,appInstalls:0,landingPageViews:0,pageLikes:0,follows:0,likes:0});};
    var calcD=function(d){d.cpm=d.impressions>0?(d.spend/d.impressions)*1000:0;d.cpc=d.clicks>0?d.spend/d.clicks:0;d.ctr=d.impressions>0?(d.clicks/d.impressions)*100:0;d.frequency=d.reach>0?d.impressions/d.reach:0;d.costPerLead=d.leads>0?d.spend/d.leads:0;d.costPerInstall=d.appInstalls>0?d.spend/d.appInstalls:0;return d;};
    var fb=calcD(sumP(fbC));var ig=calcD(sumP(igC));var mt=calcD(sumP(mc));var tt=calcD(sumP(tc));
    var ti=mt.impressions+tt.impressions,ts2=mt.spend+tt.spend,tc2=mt.clicks+tt.clicks;
    var grand={impressions:ti,spend:ts2,clicks:tc2,reach:mt.reach+tt.reach,leads:mt.leads+tt.leads,appInstalls:mt.appInstalls+tt.appInstalls,follows:mt.follows+tt.follows,pageLikes:mt.pageLikes+tt.pageLikes,likes:mt.likes+tt.likes,landingPageViews:mt.landingPageViews+tt.landingPageViews};
    grand.cpm=grand.impressions>0?(grand.spend/grand.impressions)*1000:0;grand.cpc=grand.clicks>0?grand.spend/grand.clicks:0;grand.ctr=grand.impressions>0?(grand.clicks/grand.impressions)*100:0;grand.frequency=grand.reach>0?grand.impressions/grand.reach:0;grand.costPerLead=grand.leads>0?grand.spend/grand.leads:0;
    return{fbCamps:fbC,igCamps:igC,metaCamps:mc,ttCamps:tc,fb:fb,ig:ig,meta:mt,tt:tt,grand:grand,totalImps:ti,totalSpend:ts2,totalClicks:tc2,blendedCpm:ti>0?(ts2/ti)*1000:0,allSelected:sel};
  },[campaigns,selected]);

  useEffect(function(){if(computed.meta)setFlags(genFlags(computed.meta,computed.tt,computed.allSelected||[]));},[computed]);

  var m=computed.meta,t=computed.tt;
  var ack=function(id){setFlags(function(p){return p.map(function(f){return f.id===id?Object.assign({},f,{status:"acknowledged"}):f;});});};
  var resolve=function(id){setFlags(function(p){return p.map(function(f){return f.id===id?Object.assign({},f,{status:"resolved"}):f;});});};
  var openFlags=flags.filter(function(f){return f.status==="open";}).length;

  var tabs=[{id:"overview",label:"Overview",icon:Ic.chart(P.orchid,16)},{id:"tof",label:"Ad Serving",icon:Ic.radar(P.ember,16)},{id:"mof",label:"Engagement",icon:Ic.pulse(P.mint,16)},{id:"bof",label:"Objectives",icon:Ic.target(P.rose,16)}];
  tabs.push({id:"deepdive",label:"Deep Dive",icon:Ic.eye(P.cyan,16)});if(!isClient)tabs.push({id:"optimise",label:"Optimisation"+(openFlags>0?" ("+openFlags+")":""),icon:Ic.flag(P.warning,16)});

  return(<div style={{minHeight:"100vh",background:"linear-gradient(170deg,"+P.void+","+P.cosmos+" 30%,"+P.nebula+" 60%,"+P.cosmos+")",color:P.txt,fontFamily:ff,WebkitFontSmoothing:"antialiased"}}>
    <div style={{position:"fixed",inset:0,pointerEvents:"none",zIndex:0}}><div style={{position:"absolute",inset:0,opacity:0.018,backgroundImage:"radial-gradient("+P.ember+" 0.5px,transparent 0.5px),radial-gradient("+P.orchid+" 0.5px,transparent 0.5px)",backgroundSize:"40px 40px",backgroundPosition:"0 0,20px 20px"}}/></div>

    <header style={{position:"sticky",top:0,zIndex:100,background:"rgba(6,2,14,0.92)",backdropFilter:"blur(24px)",borderBottom:"1px solid "+P.rule}}>
      <div style={{maxWidth:1400,margin:"0 auto",padding:"10px 28px"}}>
        <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:8}}>
          <div style={{display:"flex",alignItems:"center",gap:14}}>
            <div style={{width:42,height:42,borderRadius:"50%",background:gFire,display:"flex",alignItems:"center",justifyContent:"center",animation:"pulse-glow 3s ease-in-out infinite"}}><span style={{fontSize:10,fontWeight:900,color:"#fff",fontFamily:fm,letterSpacing:1}}>GAS</span></div>
            <div><div style={{fontSize:16,fontWeight:900,letterSpacing:4,fontFamily:fm,lineHeight:1}}><span style={{color:P.txt}}>MEDIA </span><span style={{color:P.ember}}>ON </span><span style={{background:gFire,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>GAS</span></div><div style={{fontSize:9,color:P.sub,letterSpacing:4,textTransform:"uppercase",fontFamily:fm,marginTop:3,fontWeight:600}}>{isClient?"Client Dashboard":"Digital Performance Intelligence"}</div></div>
          </div>
          <div style={{display:"flex",alignItems:"center",gap:6,flexWrap:"wrap"}}>
            {!isClient&&<button onClick={function(){setShowCampaigns(!showCampaigns);}} style={{background:showCampaigns?P.ember+"15":P.glass,border:"1px solid "+(showCampaigns?P.ember+"50":P.rule),borderRadius:10,padding:"8px 16px",color:showCampaigns?P.ember:P.sub,fontSize:11,fontWeight:700,fontFamily:fm,cursor:"pointer",display:"flex",alignItems:"center",gap:5}}>{Ic.chart(showCampaigns?P.ember:P.sub,14)} {selected.length} Campaigns</button>}
            <div style={{display:"flex",alignItems:"center",gap:5,background:P.glass,border:"1px solid "+P.rule,borderRadius:10,padding:"6px 12px"}}><span style={{fontSize:8,color:P.sub,fontFamily:fm,letterSpacing:2,fontWeight:700}}>FROM</span><input type="date" value={df} onChange={function(e){setDf(e.target.value);}} style={{background:"transparent",border:"none",color:"#fff",fontSize:12,fontFamily:fm,outline:"none",width:105,fontWeight:500}}/><div style={{width:12,height:1,background:"linear-gradient(90deg,"+P.ember+","+P.solar+")"}}/><span style={{fontSize:8,color:P.sub,fontFamily:fm,letterSpacing:2,fontWeight:700}}>TO</span><input type="date" value={dt} onChange={function(e){setDt(e.target.value);}} style={{background:"transparent",border:"none",color:"#fff",fontSize:12,fontFamily:fm,outline:"none",width:105,fontWeight:500}}/></div>
            <button onClick={refreshData} style={{background:gEmber,border:"none",borderRadius:10,padding:"8px 18px",color:"#fff",fontSize:11,fontWeight:800,fontFamily:fm,cursor:"pointer",letterSpacing:1.5}}>REFRESH</button>
            {!isClient&&<button onClick={function(){setShowShare(true);}} style={{background:P.glass,border:"1px solid "+P.rule,borderRadius:10,padding:"8px 12px",color:P.ember,fontSize:11,fontWeight:700,fontFamily:fm,cursor:"pointer",display:"flex",alignItems:"center",gap:4}}>{Ic.share(P.ember,14)} Share</button>}
          </div>
        </div>
      </div>
      <div style={{maxWidth:1400,margin:"0 auto",padding:"0 28px"}}><div style={{display:"flex",gap:1}}>{tabs.map(function(tb){return<button key={tb.id} onClick={function(){setTab(tb.id);}} style={{display:"flex",alignItems:"center",gap:5,background:tab===tb.id?P.ember+"10":"transparent",border:"none",borderBottom:tab===tb.id?"2px solid "+P.ember:"2px solid transparent",padding:"10px 18px",cursor:"pointer",color:tab===tb.id?P.ember:P.sub,fontSize:13,fontWeight:tab===tb.id?800:500,fontFamily:ff,letterSpacing:0.3}}>{tb.icon}<span>{tb.label}</span></button>;})}</div></div>
    </header>

    {showShare&&<ShareModal onClose={function(){setShowShare(false);}}/>}

    <div style={{maxWidth:1400,margin:"0 auto",padding:"20px 28px 80px",display:"flex",gap:20,position:"relative",zIndex:1}}>
      {showCampaigns&&<div style={{width:340,flexShrink:0}}><CampaignSelector campaigns={campaigns} selected={selected} onToggle={toggle} onSelectAll={selectAll} onClearAll={clearAll} search={search} onSearch={setSearch}/></div>}

      <div style={{flex:1,minWidth:0}}>
        {loading?(<div style={{display:"flex",flexDirection:"column",alignItems:"center",padding:"80px 40px",gap:20}}><div style={{width:48,height:48,border:"3px solid "+P.rule,borderTop:"3px solid "+P.ember,borderRadius:"50%",animation:"spin 1s linear infinite"}}/><style>{"@keyframes spin{to{transform:rotate(360deg)}}"}</style><div style={{fontSize:14,color:P.sub,fontFamily:fm}}>Pulling live data from Meta and TikTok…</div></div>):(<>

        {/* OVERVIEW */}
        {tab==="overview"&&(<div>

          <SH icon={Ic.chart(P.orchid,20)} title="Campaign Overview" sub={df+" to "+dt+" \u00b7 "+selected.length+" campaigns \u00b7 Funnel Performance Report"} accent={P.orchid}/>

          {/* ═══ AWARENESS ASSESSMENT ═══ */}
          <div style={{background:"linear-gradient(135deg, #003a55 0%, #004F71 50%, #005580 100%)",borderRadius:18,padding:"6px 24px 24px",marginBottom:28,border:"1px solid rgba(255,203,5,0.15)"}}>
            <div style={{textAlign:"center",padding:"18px 0 16px"}}><span style={{fontSize:18,fontWeight:900,color:"#fff",fontFamily:ff,letterSpacing:1}}>AWARENESS ASSESSMENT</span><div style={{fontSize:10,color:"rgba(255,255,255,0.5)",fontFamily:fm,marginTop:4,letterSpacing:3}}>TOP OF FUNNEL</div></div>

            <table style={{width:"100%",borderCollapse:"collapse",marginBottom:16}}>
              <thead><tr>{["","Media Spend","Impressions","Reach","CPM","Frequency"].map(function(h,i){return <th key={i} style={{padding:"10px 12px",fontSize:9,fontWeight:700,textTransform:"uppercase",color:"#FFCB05",textAlign:i===0?"left":"center",background:"#003a55",border:"1px solid #002a40",fontFamily:fm,letterSpacing:1}}>{h}</th>;})}</tr></thead>
              <tbody>
                <tr style={{background:"rgba(69,153,255,0.08)"}}><td style={{padding:"12px",border:"1px solid #002a40",display:"flex",alignItems:"center",gap:8}}><span style={{width:10,height:10,borderRadius:"50%",background:P.fb}}></span><span style={{fontSize:12,fontWeight:700,color:"#fff"}}>Facebook</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#fff",fontFamily:fm,fontSize:13,fontWeight:700}}>{fR(computed.fb.spend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#fff",fontFamily:fm,fontSize:13}}>{fmt(computed.fb.impressions)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#fff",fontFamily:fm,fontSize:13}}>{fmt(computed.fb.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:computed.fb.cpm<15?P.mint:P.warning,fontFamily:fm,fontSize:13,fontWeight:700}}>{fR(computed.fb.cpm)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:computed.fb.frequency>3?P.warning:"#fff",fontFamily:fm,fontSize:13,fontWeight:700}}>{computed.fb.frequency>0?computed.fb.frequency.toFixed(2)+"x":"\u2014"}</td></tr>
                <tr style={{background:"rgba(225,48,108,0.08)"}}><td style={{padding:"12px",border:"1px solid #002a40",display:"flex",alignItems:"center",gap:8}}><span style={{width:10,height:10,borderRadius:"50%",background:P.ig}}></span><span style={{fontSize:12,fontWeight:700,color:"#fff"}}>Instagram</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#fff",fontFamily:fm,fontSize:13,fontWeight:700}}>{fR(computed.ig.spend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#fff",fontFamily:fm,fontSize:13}}>{fmt(computed.ig.impressions)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#fff",fontFamily:fm,fontSize:13}}>{fmt(computed.ig.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:computed.ig.cpm<15?P.mint:P.warning,fontFamily:fm,fontSize:13,fontWeight:700}}>{fR(computed.ig.cpm)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:computed.ig.frequency>3?P.warning:"#fff",fontFamily:fm,fontSize:13,fontWeight:700}}>{computed.ig.frequency>0?computed.ig.frequency.toFixed(2)+"x":"\u2014"}</td></tr>
                <tr style={{background:"rgba(69,153,255,0.15)"}}><td style={{padding:"12px",border:"1px solid #002a40"}}><span style={{fontSize:12,fontWeight:900,color:P.fb}}>Meta Total</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{fR(m.spend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{fmt(m.impressions)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{fmt(m.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{fR(m.cpm)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{m.frequency>0?m.frequency.toFixed(2)+"x":"\u2014"}</td></tr>
                <tr style={{background:"rgba(0,242,234,0.08)"}}><td style={{padding:"12px",border:"1px solid #002a40",display:"flex",alignItems:"center",gap:8}}><span style={{width:10,height:10,borderRadius:"50%",background:P.tt}}></span><span style={{fontSize:12,fontWeight:700,color:"#fff"}}>TikTok</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#fff",fontFamily:fm,fontSize:13,fontWeight:700}}>{fR(t.spend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#fff",fontFamily:fm,fontSize:13}}>{fmt(t.impressions)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#fff",fontFamily:fm,fontSize:13}}>\u2014</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:t.cpm<15?P.mint:P.warning,fontFamily:fm,fontSize:13,fontWeight:700}}>{fR(t.cpm)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#fff",fontFamily:fm,fontSize:13}}>\u2014</td></tr>
                <tr style={{background:"rgba(255,107,0,0.15)"}}><td style={{padding:"12px",border:"1px solid #002a40"}}><span style={{fontSize:13,fontWeight:900,color:"#FFCB05"}}>GRAND TOTAL</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#FFCB05",fontFamily:fm,fontSize:15,fontWeight:900}}>{fR(computed.totalSpend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#FFCB05",fontFamily:fm,fontSize:15,fontWeight:900}}>{fmt(computed.totalImps)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#FFCB05",fontFamily:fm,fontSize:15,fontWeight:900}}>{fmt(computed.grand.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#FFCB05",fontFamily:fm,fontSize:15,fontWeight:900}}>{fR(computed.blendedCpm)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid #002a40",color:"#FFCB05",fontFamily:fm,fontSize:15,fontWeight:900}}>{computed.grand.frequency>0?computed.grand.frequency.toFixed(2)+"x":"\u2014"}</td></tr>
              </tbody>
            </table>

            <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,marginBottom:16}}>
              <div style={{background:"rgba(0,0,0,0.2)",borderRadius:12,padding:20}}><div style={{fontSize:10,fontWeight:800,color:"rgba(255,255,255,0.5)",letterSpacing:3,fontFamily:fm,textTransform:"uppercase",marginBottom:14}}>Impressions & Reach by Platform</div><ResponsiveContainer width="100%" height={200}><BarChart data={[{name:"Facebook",Impressions:computed.fb.impressions,Reach:computed.fb.reach},{name:"Instagram",Impressions:computed.ig.impressions,Reach:computed.ig.reach},{name:"TikTok",Impressions:t.impressions,Reach:0}]} barSize={20}><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.1)"/><XAxis dataKey="name" tick={{fontSize:11,fill:"#fff",fontFamily:fm}} stroke="transparent"/><YAxis tick={{fontSize:10,fill:"rgba(255,255,255,0.4)",fontFamily:fm}} stroke="transparent" tickFormatter={function(v){return fmt(v);}}/><Tooltip content={Tip}/><Bar dataKey="Impressions" fill={P.cyan} radius={[6,6,0,0]}/><Bar dataKey="Reach" fill={P.orchid} radius={[6,6,0,0]}/></BarChart></ResponsiveContainer><div style={{display:"flex",justifyContent:"center",gap:16,marginTop:8}}><div style={{display:"flex",alignItems:"center",gap:4}}><span style={{width:8,height:8,borderRadius:2,background:P.cyan}}></span><span style={{fontSize:10,color:"rgba(255,255,255,0.6)",fontFamily:fm}}>Impressions</span></div><div style={{display:"flex",alignItems:"center",gap:4}}><span style={{width:8,height:8,borderRadius:2,background:P.orchid}}></span><span style={{fontSize:10,color:"rgba(255,255,255,0.6)",fontFamily:fm}}>Reach</span></div></div></div>
              <div style={{background:"rgba(0,0,0,0.2)",borderRadius:12,padding:20}}><div style={{fontSize:10,fontWeight:800,color:"rgba(255,255,255,0.5)",letterSpacing:3,fontFamily:fm,textTransform:"uppercase",marginBottom:14}}>Spend Allocation</div><ResponsiveContainer width="100%" height={200}><PieChart><Pie data={[{name:"Facebook",value:computed.fb.spend},{name:"Instagram",value:computed.ig.spend},{name:"TikTok",value:t.spend}]} cx="50%" cy="50%" outerRadius={72} innerRadius={44} paddingAngle={4} dataKey="value" stroke="none"><Cell fill={P.fb}/><Cell fill={P.ig}/><Cell fill={P.tt}/></Pie><Tooltip content={Tip}/></PieChart></ResponsiveContainer><div style={{display:"flex",justifyContent:"center",gap:12,marginTop:8}}>{[{n:"FB",v:computed.fb.spend,c:P.fb},{n:"IG",v:computed.ig.spend,c:P.ig},{n:"TT",v:t.spend,c:P.tt}].map(function(p){return <div key={p.n} style={{display:"flex",alignItems:"center",gap:4}}><span style={{width:8,height:8,borderRadius:"50%",background:p.c}}></span><span style={{fontSize:10,color:"rgba(255,255,255,0.6)",fontFamily:fm}}>{p.n} {fR(p.v)}</span></div>;})}</div></div>
            </div>

            <Insight title="Awareness Analysis" accent={P.cyan} icon={Ic.eye(P.cyan,16)}>The campaign has served <strong>{fmt(computed.totalImps)} impressions</strong> across Facebook ({fmt(computed.fb.impressions)}), Instagram ({fmt(computed.ig.impressions)}), and TikTok ({fmt(t.impressions)}) against <strong>{fR(computed.totalSpend)}</strong> total investment. Facebook delivers the richest audience data with {fmt(computed.fb.reach)} unique reach at {computed.fb.frequency>0?computed.fb.frequency.toFixed(2)+"x":"N/A"} frequency, whilst TikTok provides the most cost-efficient impressions at {fR(t.cpm)} CPM. The blended campaign CPM of <strong>{fR(computed.blendedCpm)}</strong> represents strong media value in the South African paid social market. {computed.fb.frequency>3?"Warning: Facebook frequency at "+computed.fb.frequency.toFixed(2)+"x is approaching the fatigue threshold \u2014 consider audience expansion or creative refresh.":""}</Insight>
          </div>

          {/* \u2550\u2550\u2550 ENGAGEMENT ASSESSMENT \u2550\u2550\u2550 */}
          <div style={{background:P.glass,borderRadius:18,padding:"6px 24px 24px",marginBottom:28,border:"1px solid "+P.rule}}>
            <div style={{textAlign:"center",padding:"18px 0 16px"}}><span style={{fontSize:18,fontWeight:900,color:P.txt,fontFamily:ff,letterSpacing:1}}>ENGAGEMENT ASSESSMENT</span><div style={{fontSize:10,color:P.sub,fontFamily:fm,marginTop:4,letterSpacing:3}}>MIDDLE OF FUNNEL</div></div>

            <table style={{width:"100%",borderCollapse:"collapse",marginBottom:16}}>
              <thead><tr>{["","Media Spend","Reach","Clicks","CTR %","CPC"].map(function(h,i){return <th key={i} style={{padding:"10px 12px",fontSize:9,fontWeight:700,textTransform:"uppercase",color:"#FFCB05",textAlign:i===0?"left":"center",background:"#004F71",border:"1px solid #003a55",fontFamily:fm,letterSpacing:1}}>{h}</th>;})}</tr></thead>
              <tbody>
                <tr style={{background:"rgba(69,153,255,0.06)"}}><td style={{padding:"12px",border:"1px solid "+P.rule,display:"flex",alignItems:"center",gap:8}}><span style={{width:10,height:10,borderRadius:"50%",background:P.fb}}></span><span style={{fontSize:12,fontWeight:700,color:P.txt}}>Facebook</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13,fontWeight:700}}>{fR(computed.fb.spend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13}}>{fmt(computed.fb.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13,fontWeight:700}}>{fmt(computed.fb.clicks)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:computed.fb.ctr>2?P.mint:computed.fb.ctr>1?P.txt:P.warning,fontFamily:fm,fontSize:13,fontWeight:700}}>{pc(computed.fb.ctr)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:computed.fb.cpc<2?P.mint:P.txt,fontFamily:fm,fontSize:13,fontWeight:700}}>{fR(computed.fb.cpc)}</td></tr>
                <tr style={{background:"rgba(225,48,108,0.06)"}}><td style={{padding:"12px",border:"1px solid "+P.rule,display:"flex",alignItems:"center",gap:8}}><span style={{width:10,height:10,borderRadius:"50%",background:P.ig}}></span><span style={{fontSize:12,fontWeight:700,color:P.txt}}>Instagram</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13,fontWeight:700}}>{fR(computed.ig.spend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13}}>{fmt(computed.ig.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13,fontWeight:700}}>{fmt(computed.ig.clicks)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:computed.ig.ctr>2?P.mint:computed.ig.ctr>1?P.txt:P.warning,fontFamily:fm,fontSize:13,fontWeight:700}}>{pc(computed.ig.ctr)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:computed.ig.cpc<2?P.mint:P.txt,fontFamily:fm,fontSize:13,fontWeight:700}}>{fR(computed.ig.cpc)}</td></tr>
                <tr style={{background:"rgba(69,153,255,0.12)"}}><td style={{padding:"12px",border:"1px solid "+P.rule}}><span style={{fontSize:12,fontWeight:900,color:P.fb}}>Meta Total</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{fR(m.spend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{fmt(m.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{fmt(m.clicks)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{pc(m.ctr)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{fR(m.cpc)}</td></tr>
                <tr style={{background:"rgba(0,242,234,0.06)"}}><td style={{padding:"12px",border:"1px solid "+P.rule,display:"flex",alignItems:"center",gap:8}}><span style={{width:10,height:10,borderRadius:"50%",background:P.tt}}></span><span style={{fontSize:12,fontWeight:700,color:P.txt}}>TikTok</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13,fontWeight:700}}>{fR(t.spend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13}}>\u2014</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13,fontWeight:700}}>{fmt(t.clicks)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13}}>\u2014</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13}}>\u2014</td></tr>
                <tr style={{background:"rgba(255,107,0,0.12)"}}><td style={{padding:"12px",border:"1px solid "+P.rule}}><span style={{fontSize:13,fontWeight:900,color:P.ember}}>GRAND TOTAL</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{fR(computed.totalSpend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{fmt(computed.grand.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{fmt(computed.totalClicks)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{pc(computed.grand.ctr)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{fR(computed.grand.cpc)}</td></tr>
              </tbody>
            </table>

            <div style={{background:"rgba(0,0,0,0.15)",borderRadius:12,padding:20,marginBottom:16}}><div style={{fontSize:10,fontWeight:800,color:P.sub,letterSpacing:3,fontFamily:fm,textTransform:"uppercase",marginBottom:14}}>Clicks & CPC by Platform</div><ResponsiveContainer width="100%" height={200}><BarChart data={[{name:"Facebook",Clicks:computed.fb.clicks,CPC:computed.fb.cpc},{name:"Instagram",Clicks:computed.ig.clicks,CPC:computed.ig.cpc},{name:"TikTok",Clicks:t.clicks,CPC:t.clicks>0?t.spend/t.clicks:0}]}><CartesianGrid strokeDasharray="3 3" stroke={P.rule}/><XAxis dataKey="name" tick={{fontSize:11,fill:P.txt,fontFamily:fm}} stroke="transparent"/><YAxis tick={{fontSize:10,fill:P.dim,fontFamily:fm}} stroke="transparent" tickFormatter={function(v){return fmt(v);}}/><Tooltip content={Tip}/><Bar dataKey="Clicks" fill={P.mint} radius={[6,6,0,0]} barSize={30}/></BarChart></ResponsiveContainer></div>

            <Insight title="Engagement Analysis" accent={P.mint} icon={Ic.pulse(P.mint,16)}>Facebook has generated <strong>{fmt(computed.fb.clicks)} clicks</strong> at <strong>{fR(computed.fb.cpc)} CPC</strong> with {pc(computed.fb.ctr)} CTR, confirming strong creative-audience alignment on the platform. Instagram contributed {fmt(computed.ig.clicks)} clicks at {fR(computed.ig.cpc)} CPC with {pc(computed.ig.ctr)} CTR. The combined Meta engagement of <strong>{fmt(m.clicks)} clicks</strong> at {fR(m.cpc)} blended CPC represents efficient conversion of awareness into measurable intent signals. TikTok contributed {fmt(t.clicks)} clicks through its performance network, with engagement metrics carrying additional amplification value as TikTok\u2019s algorithm promotes content with strong interaction signals. {m.cpc<2?"Meta CPC below R2.00 is a positive efficiency signal \u2014 consider scaling budget on top-performing ad sets.":m.cpc>5?"Meta CPC above R5.00 warrants creative review and potential audience refresh.":""}</Insight>
          </div>

          {/* \u2550\u2550\u2550 OBJECTIVE ASSESSMENT \u2550\u2550\u2550 */}
          <div style={{background:P.glass,borderRadius:18,padding:"6px 24px 24px",marginBottom:28,border:"1px solid "+P.rule}}>
            <div style={{textAlign:"center",padding:"18px 0 16px"}}><span style={{fontSize:18,fontWeight:900,color:P.txt,fontFamily:ff,letterSpacing:1}}>OBJECTIVE ASSESSMENT</span><div style={{fontSize:10,color:P.sub,fontFamily:fm,marginTop:4,letterSpacing:3}}>BOTTOM OF FUNNEL</div></div>

            {computed.grand.leads>0&&<div style={{marginBottom:20}}>
              <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:12}}><span style={{width:10,height:10,borderRadius:"50%",background:P.rose}}></span><span style={{fontSize:13,fontWeight:800,color:P.rose,fontFamily:ff}}>Lead Generation</span></div>
              <table style={{width:"100%",borderCollapse:"collapse",marginBottom:12}}>
                <thead><tr>{["","Media Spend","Reach","Clicks","Leads","Cost Per Lead"].map(function(h,i){return <th key={i} style={{padding:"10px 12px",fontSize:9,fontWeight:700,textTransform:"uppercase",color:"#FFCB05",textAlign:i===0?"left":"center",background:"#004F71",border:"1px solid #003a55",fontFamily:fm}}>{h}</th>;})}</tr></thead>
                <tbody>
                  <tr style={{background:"rgba(69,153,255,0.06)"}}><td style={{padding:"12px",border:"1px solid "+P.rule,display:"flex",alignItems:"center",gap:8}}><span style={{width:10,height:10,borderRadius:"50%",background:P.fb}}></span><span style={{fontSize:12,fontWeight:700,color:P.txt}}>Facebook</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13}}>{fR(computed.fb.spend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13}}>{fmt(computed.fb.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13}}>{fmt(computed.fb.clicks)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.mint,fontFamily:fm,fontSize:14,fontWeight:900}}>{fmt(computed.fb.leads)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:14,fontWeight:900}}>{computed.fb.leads>0?fR(computed.fb.costPerLead):"\u2014"}</td></tr>
                  <tr style={{background:"rgba(225,48,108,0.06)"}}><td style={{padding:"12px",border:"1px solid "+P.rule,display:"flex",alignItems:"center",gap:8}}><span style={{width:10,height:10,borderRadius:"50%",background:P.ig}}></span><span style={{fontSize:12,fontWeight:700,color:P.txt}}>Instagram</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13}}>{fR(computed.ig.spend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13}}>{fmt(computed.ig.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.txt,fontFamily:fm,fontSize:13}}>{fmt(computed.ig.clicks)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.mint,fontFamily:fm,fontSize:14,fontWeight:900}}>{fmt(computed.ig.leads)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:14,fontWeight:900}}>{computed.ig.leads>0?fR(computed.ig.costPerLead):"\u2014"}</td></tr>
                  <tr style={{background:"rgba(69,153,255,0.12)"}}><td style={{padding:"12px",border:"1px solid "+P.rule}}><span style={{fontSize:12,fontWeight:900,color:P.fb}}>Meta Total</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{fR(m.spend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{fmt(m.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.fb,fontFamily:fm,fontSize:14,fontWeight:900}}>{fmt(m.clicks)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.fb,fontFamily:fm,fontSize:15,fontWeight:900}}>{fmt(m.leads)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.fb,fontFamily:fm,fontSize:15,fontWeight:900}}>{m.leads>0?fR(m.costPerLead):"\u2014"}</td></tr>
                  <tr style={{background:"rgba(255,107,0,0.12)"}}><td style={{padding:"12px",border:"1px solid "+P.rule}}><span style={{fontSize:13,fontWeight:900,color:P.ember}}>TOTAL</span></td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{fR(computed.totalSpend)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{fmt(computed.grand.reach)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:15,fontWeight:900}}>{fmt(computed.totalClicks)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:16,fontWeight:900}}>{fmt(computed.grand.leads)}</td><td style={{padding:"12px",textAlign:"center",border:"1px solid "+P.rule,color:P.ember,fontFamily:fm,fontSize:16,fontWeight:900}}>{computed.grand.leads>0?fR(computed.grand.costPerLead):"\u2014"}</td></tr>
                </tbody>
              </table>
              <Insight title="Lead Generation Performance" accent={P.rose} icon={Ic.target(P.rose,16)}>The lead generation campaigns have delivered <strong>{fmt(computed.grand.leads)} leads</strong> at <strong>{computed.grand.leads>0?fR(computed.grand.spend/computed.grand.leads):"N/A"} cost per lead</strong>. Facebook contributed {fmt(computed.fb.leads)} leads at {computed.fb.leads>0?fR(computed.fb.costPerLead):"N/A"} CPL, whilst Instagram generated {fmt(computed.ig.leads)} leads at {computed.ig.leads>0?fR(computed.ig.costPerLead):"N/A"} CPL. {computed.fb.leads>0&&computed.ig.leads>0&&computed.ig.costPerLead<computed.fb.costPerLead?"Instagram is delivering leads more cost-efficiently than Facebook \u2014 consider reallocating a portion of Facebook lead budget to Instagram to optimise blended CPL.":""}The quality of these leads should be validated against downstream conversion metrics to confirm they are translating into meaningful business outcomes.</Insight>
            </div>}

            {t.follows>0&&<div style={{marginBottom:20}}>
              <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:12}}><span style={{width:10,height:10,borderRadius:"50%",background:P.tt}}></span><span style={{fontSize:13,fontWeight:800,color:P.tt,fontFamily:ff}}>Community Growth (Follows)</span></div>
              <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:14}}>
                <Glass accent={P.tt} hv={true} st={{padding:20,textAlign:"center"}}><div style={{fontSize:9,color:P.dim,fontFamily:fm,letterSpacing:2,marginBottom:8}}>TT FOLLOWS</div><div style={{fontSize:28,fontWeight:900,color:P.mint,fontFamily:fm}}>{fmt(t.follows)}</div></Glass>
                <Glass accent={P.tt} hv={true} st={{padding:20,textAlign:"center"}}><div style={{fontSize:9,color:P.dim,fontFamily:fm,letterSpacing:2,marginBottom:8}}>COST PER FOLLOW</div><div style={{fontSize:28,fontWeight:900,color:P.tt,fontFamily:fm}}>{t.follows>0?fR(t.spend/t.follows):"\u2014"}</div></Glass>
                <Glass accent={P.tt} hv={true} st={{padding:20,textAlign:"center"}}><div style={{fontSize:9,color:P.dim,fontFamily:fm,letterSpacing:2,marginBottom:8}}>TT LIKES</div><div style={{fontSize:28,fontWeight:900,color:P.fuchsia,fontFamily:fm}}>{fmt(t.likes)}</div></Glass>
              </div>
              <Insight title="Community Acquisition" accent={P.tt} icon={Ic.users(P.tt,16)}>TikTok has acquired <strong>{fmt(t.follows)} followers</strong> at {t.follows>0?fR(t.spend/t.follows):"N/A"} cost per follow, building a compounding organic asset that reduces future paid media dependency. Each follower increases organic content reach, provides a retargetable first-party audience, and signals brand affinity to TikTok\u2019s recommendation engine. {t.likes>0?"The "+fmt(t.likes)+" engagements earned further amplify content distribution through TikTok\u2019s algorithm, effectively delivering bonus organic impressions at zero marginal cost.":""}</Insight>
            </div>}

            {m.appInstalls>0&&<div style={{marginBottom:20}}>
              <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:12}}><span style={{width:10,height:10,borderRadius:"50%",background:P.fb}}></span><span style={{fontSize:13,fontWeight:800,color:P.fb,fontFamily:ff}}>App Install Clicks</span></div>
              <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:14}}>
                <Glass accent={P.fb} hv={true} st={{padding:20,textAlign:"center"}}><div style={{fontSize:9,color:P.dim,fontFamily:fm,letterSpacing:2,marginBottom:8}}>APP CLICKS</div><div style={{fontSize:28,fontWeight:900,color:P.fb,fontFamily:fm}}>{fmt(m.appInstalls)}</div></Glass>
                <Glass accent={P.fb} hv={true} st={{padding:20,textAlign:"center"}}><div style={{fontSize:9,color:P.dim,fontFamily:fm,letterSpacing:2,marginBottom:8}}>COST PER INSTALL</div><div style={{fontSize:28,fontWeight:900,color:P.ember,fontFamily:fm}}>{m.appInstalls>0?fR(m.costPerInstall):"\u2014"}</div></Glass>
                <Glass accent={P.fb} hv={true} st={{padding:20,textAlign:"center"}}><div style={{fontSize:9,color:P.dim,fontFamily:fm,letterSpacing:2,marginBottom:8}}>TOTAL SPEND</div><div style={{fontSize:28,fontWeight:900,color:P.solar,fontFamily:fm}}>{fR(m.spend)}</div></Glass>
              </div>
            </div>}
          </div>

          {/* \u2550\u2550\u2550 COMMUNITY GROWTH \u2550\u2550\u2550 */}
          <div style={{background:P.glass,borderRadius:18,padding:"6px 24px 24px",marginBottom:28,border:"1px solid "+P.rule}}>
            <div style={{textAlign:"center",padding:"18px 0 16px"}}><span style={{fontSize:18,fontWeight:900,color:P.txt,fontFamily:ff,letterSpacing:1}}>COMMUNITY GROWTH</span><div style={{fontSize:10,color:P.sub,fontFamily:fm,marginTop:4,letterSpacing:3}}>PAGE LIKES & FOLLOWS BY PLATFORM</div></div>

            <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:16,marginBottom:20}}>
              <Glass accent={P.fb} hv={true} st={{padding:22,textAlign:"center"}}><div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:6,marginBottom:10}}><span style={{width:10,height:10,borderRadius:"50%",background:P.fb}}></span><span style={{fontSize:11,fontWeight:700,color:P.fb,fontFamily:fm}}>FACEBOOK</span></div><div style={{fontSize:9,color:P.dim,fontFamily:fm,letterSpacing:2,marginBottom:6}}>PAGE LIKES</div><div style={{fontSize:32,fontWeight:900,color:P.fb,fontFamily:fm}}>{fmt(m.pageLikes)}</div></Glass>
              <Glass accent={P.ig} hv={true} st={{padding:22,textAlign:"center"}}><div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:6,marginBottom:10}}><span style={{width:10,height:10,borderRadius:"50%",background:P.ig}}></span><span style={{fontSize:11,fontWeight:700,color:P.ig,fontFamily:fm}}>INSTAGRAM</span></div><div style={{fontSize:9,color:P.dim,fontFamily:fm,letterSpacing:2,marginBottom:6}}>FOLLOWERS</div><div style={{fontSize:32,fontWeight:900,color:P.ig,fontFamily:fm}}>{fmt(computed.ig.pageLikes)}</div></Glass>
              <Glass accent={P.tt} hv={true} st={{padding:22,textAlign:"center"}}><div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:6,marginBottom:10}}><span style={{width:10,height:10,borderRadius:"50%",background:P.tt}}></span><span style={{fontSize:11,fontWeight:700,color:P.tt,fontFamily:fm}}>TIKTOK</span></div><div style={{fontSize:9,color:P.dim,fontFamily:fm,letterSpacing:2,marginBottom:6}}>FOLLOWS</div><div style={{fontSize:32,fontWeight:900,color:P.tt,fontFamily:fm}}>{fmt(t.follows)}</div></Glass>
            </div>

            <div style={{background:"rgba(0,0,0,0.15)",borderRadius:12,padding:20,marginBottom:16}}><div style={{fontSize:10,fontWeight:800,color:P.sub,letterSpacing:3,fontFamily:fm,textTransform:"uppercase",marginBottom:14}}>Community by Platform</div><ResponsiveContainer width="100%" height={200}><BarChart data={[{name:"FB Likes",value:m.pageLikes,fill:P.fb},{name:"IG Follows",value:computed.ig.pageLikes,fill:P.ig},{name:"TT Follows",value:t.follows,fill:P.tt}]} barSize={40}><CartesianGrid strokeDasharray="3 3" stroke={P.rule}/><XAxis dataKey="name" tick={{fontSize:11,fill:P.txt,fontFamily:fm}} stroke="transparent"/><YAxis tick={{fontSize:10,fill:P.dim,fontFamily:fm}} stroke="transparent" tickFormatter={function(v){return fmt(v);}}/><Tooltip content={Tip}/><Bar dataKey="value" radius={[8,8,0,0]}><Cell fill={P.fb}/><Cell fill={P.ig}/><Cell fill={P.tt}/></Bar></BarChart></ResponsiveContainer></div>

            <Insight title="Community Value Assessment" accent={P.fuchsia} icon={Ic.users(P.fuchsia,16)}>The combined community growth of <strong>{fmt(m.pageLikes+computed.ig.pageLikes+t.follows)} new members</strong> across Facebook ({fmt(m.pageLikes)} page likes), Instagram ({fmt(computed.ig.pageLikes)} followers), and TikTok ({fmt(t.follows)} follows) represents a growing owned audience asset. Each community member reduces future paid media dependency by increasing organic content reach. Facebook page likes carry the highest organic reach weighting in Meta\u2019s algorithm, Instagram followers drive Stories and Reels visibility, and TikTok follows feed directly into the For You page recommendation engine. This three-platform community strategy ensures brand presence across the dominant social ecosystems in South Africa.</Insight>
          </div>

        </div>)}

        {tab==="tof"&&(<div>
          <SH icon={Ic.radar(P.ember,20)} title="Top of Funnel — Ad Serving" sub="Impressions · Reach · Frequency · CPM" accent={P.ember}/>
          <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginBottom:24}}><Metric icon={Ic.eye(P.cyan,14)} label="Impressions" value={fmt(computed.totalImps)} accent={P.cyan}/><Metric icon={Ic.users(P.orchid,14)} label="Meta Reach" value={fmt(m.reach)} accent={P.orchid}/><Metric icon={Ic.radar(P.rose,14)} label="Frequency" value={m.frequency>0?m.frequency.toFixed(2)+"x":"N/A"} accent={P.rose}/><Metric icon={Ic.bolt(P.mint,14)} label="Blended CPM" value={fR(computed.blendedCpm)} accent={P.mint}/></div>

          <PH platform="Facebook" suffix="Campaign Performance"/>
          <Glass accent={P.fb} st={{padding:22,marginBottom:20}}>
            <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14,marginBottom:14}}>{[{l:"Impressions",v:fmt(m.impressions)},{l:"Reach",v:fmt(m.reach)},{l:"Frequency",v:m.frequency>0?m.frequency.toFixed(2)+"x":"N/A"},{l:"CPM",v:fR(m.cpm)}].map(function(x,i){return<div key={i} style={{textAlign:"center"}}><div style={{fontSize:9,color:P.dim,fontFamily:fm,letterSpacing:2,marginBottom:4}}>{x.l}</div><div style={{fontSize:20,fontWeight:900,color:P.fb,fontFamily:fm}}>{x.v}</div></div>;})}</div>
            {computed.metaCamps.length>0&&<table style={{width:"100%",borderCollapse:"collapse",marginBottom:14}}><thead><tr>{["Campaign","Impressions","Spend","CPC","CTR"].map(function(h,i){return<th key={i} style={{padding:"10px 14px",fontSize:9,fontWeight:700,textTransform:"uppercase",color:"#FFCB05",textAlign:i===0?"left":"center",background:"#004F71",border:"1px solid #003a55",fontFamily:fm}}>{h}</th>;})}</tr></thead><tbody>{computed.metaCamps.sort(function(a,b){return parseFloat(b.impressions)-parseFloat(a.impressions);}).map(function(c,i){return<tr key={i} style={{background:i%2===0?"rgba(240,246,251,0.04)":"transparent"}}><td style={{padding:"10px 14px",fontSize:11,fontWeight:600,color:P.txt,border:"1px solid "+P.rule}}>{c.campaignName}</td><td style={{padding:"10px 14px",fontSize:12,color:P.txt,textAlign:"center",border:"1px solid "+P.rule,fontFamily:fm}}>{fmt(c.impressions)}</td><td style={{padding:"10px 14px",fontSize:12,color:P.txt,textAlign:"center",border:"1px solid "+P.rule,fontFamily:fm}}>{fR(parseFloat(c.spend))}</td><td style={{padding:"10px 14px",fontSize:12,color:P.mint,textAlign:"center",border:"1px solid "+P.rule,fontFamily:fm,fontWeight:700}}>{fR(parseFloat(c.cpc||0))}</td><td style={{padding:"10px 14px",fontSize:12,color:P.txt,textAlign:"center",border:"1px solid "+P.rule,fontFamily:fm}}>{pc(parseFloat(c.ctr||0))}</td></tr>;})}</tbody></table>}
            <Insight title="Meta Campaign Read" accent={P.fb} icon={Ic.bolt(P.fb,16)}>Meta has delivered <strong>{fmt(m.impressions)} impressions</strong> reaching <strong>{fmt(m.reach)} unique individuals</strong> at {m.frequency>0?m.frequency.toFixed(2)+"x":"N/A"} frequency and {fR(m.cpm)} CPM. The {fmt(m.clicks)} clicks generated at {fR(m.cpc)} CPC with {pc(m.ctr)} CTR against {fR(m.spend)} investment confirms the algorithm has successfully identified and is consistently reaching high-intent audience pockets. The frequency level indicates the campaign is within the optimal exposure window — sufficient repetition to build recall without crossing into diminishing returns territory. The platform’s publisher breakdown capabilities are automatically optimising delivery across Facebook feed, Instagram Stories, Reels, and the Audience Network to find the lowest-cost conversion opportunities within each placement.</Insight>
          </Glass>

          <PH platform="TikTok" suffix="Campaign Performance"/>
          <Glass accent={P.tt} st={{padding:22,marginBottom:20}}>
            <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14,marginBottom:14}}>{[{l:"Impressions",v:fmt(t.impressions)},{l:"CPM",v:fR(t.cpm)},{l:"Follows",v:fmt(t.follows)},{l:"Spend",v:fR(t.spend)}].map(function(x,i){return<div key={i} style={{textAlign:"center"}}><div style={{fontSize:9,color:P.dim,fontFamily:fm,letterSpacing:2,marginBottom:4}}>{x.l}</div><div style={{fontSize:20,fontWeight:900,color:P.tt,fontFamily:fm}}>{x.v}</div></div>;})}</div>
            {computed.ttCamps.length>0&&<table style={{width:"100%",borderCollapse:"collapse",marginBottom:14}}><thead><tr>{["Campaign","Impressions","Spend","CPM"].map(function(h,i){return<th key={i} style={{padding:"10px 14px",fontSize:9,fontWeight:700,textTransform:"uppercase",color:"#fff",textAlign:i===0?"left":"center",background:"#252538",border:"1px solid #3a3a4e",fontFamily:fm}}>{h}</th>;})}</tr></thead><tbody>{computed.ttCamps.sort(function(a,b){return parseFloat(b.impressions)-parseFloat(a.impressions);}).map(function(c,i){return<tr key={i} style={{background:i%2===0?"#1e1e2e":"#252538"}}><td style={{padding:"10px 14px",fontSize:11,fontWeight:600,color:"#fff",border:"1px solid #3a3a4e"}}>{c.campaignName}</td><td style={{padding:"10px 14px",fontSize:12,color:"#fff",textAlign:"center",border:"1px solid #3a3a4e",fontFamily:fm}}>{fmt(c.impressions)}</td><td style={{padding:"10px 14px",fontSize:12,color:"#ccc",textAlign:"center",border:"1px solid #3a3a4e",fontFamily:fm}}>{fR(parseFloat(c.spend))}</td><td style={{padding:"10px 14px",fontSize:12,color:P.tt,textAlign:"center",border:"1px solid #3a3a4e",fontFamily:fm,fontWeight:700}}>{fR(parseFloat(c.cpm||0))}</td></tr>;})}</tbody></table>}
            <Insight title="TikTok Campaign Read" accent={P.tt} icon={Ic.bolt(P.tt,16)}>TikTok has delivered <strong>{fmt(t.impressions)} impressions</strong> at <strong>{fR(t.cpm)} CPM</strong> with {fmt(t.follows)} followers and {fmt(t.likes)} engagements against {fR(t.spend)} investment. The platform’s content-first algorithm is rewarding the campaign creative with favourable auction positioning, evidenced by the below-market CPM. TikTok’s unique strength lies in its ability to drive simultaneous paid and organic amplification — when paid creative resonates, TikTok’s recommendation engine extends its distribution beyond the paid audience, effectively delivering bonus organic impressions at zero marginal cost. The follower acquisition is particularly valuable: each new follow creates a persistent organic distribution channel that reduces future paid media dependency.</Insight>
          </Glass>

          <Glass st={{padding:22}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:16}}>{Ic.chart(P.ember,16)}<span style={{fontSize:10,fontWeight:800,color:P.ember,letterSpacing:3,fontFamily:fm,textTransform:"uppercase"}}>Impression Volume</span></div><ResponsiveContainer width="100%" height={200}><BarChart data={[{name:"Meta",Impressions:m.impressions},{name:"TikTok",Impressions:t.impressions}]} barSize={60}><CartesianGrid strokeDasharray="3 3" stroke={P.rule}/><XAxis dataKey="name" tick={{fontSize:12,fill:P.txt,fontFamily:fm}} stroke="transparent"/><YAxis tick={{fontSize:10,fill:P.dim,fontFamily:fm}} stroke="transparent" tickFormatter={function(v){return fmt(v);}}/><Tooltip content={Tip}/><Bar dataKey="Impressions" radius={[12,12,0,0]}><Cell fill={P.fb}/><Cell fill={P.tt}/></Bar></BarChart></ResponsiveContainer></Glass>
        </div>)}

        {/* ENGAGEMENT */}
        {tab==="mof"&&(<div>
          <SH icon={Ic.pulse(P.mint,20)} title="Middle of Funnel — Engagement" sub="Clicks · CTR · CPC · Top Campaigns" accent={P.mint}/>
          <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginBottom:24}}><Metric icon={Ic.pulse(P.mint,14)} label="Total Clicks" value={fmt(computed.totalClicks)} accent={P.mint}/><Metric icon={Ic.bolt(P.solar,14)} label="Meta CPC" value={fR(m.cpc)} accent={P.solar}/><Metric icon={Ic.eye(P.cyan,14)} label="Meta CTR" value={pc(m.ctr)} accent={P.cyan}/><Metric icon={Ic.users(P.fuchsia,14)} label="TT Follows" value={fmt(t.follows)} accent={P.fuchsia}/></div>

          <PH platform="Facebook" suffix="Top Campaigns by Clicks"/>
          <Glass accent={P.fb} st={{padding:22,marginBottom:20}}>
            {computed.metaCamps.sort(function(a,b){return parseFloat(b.clicks||0)-parseFloat(a.clicks||0);}).slice(0,8).map(function(c,i){var best=i===0;return<div key={i} style={{display:"flex",alignItems:"center",gap:12,padding:"12px 16px",marginBottom:4,background:i%2===0?P.orchid+"06":"transparent",borderRadius:10,borderLeft:"3px solid "+(best?P.solar:P.fb)}}>
              <div style={{width:28,height:28,borderRadius:8,background:best?P.solar+"15":P.fb+"10",display:"flex",alignItems:"center",justifyContent:"center",fontSize:13,fontWeight:900,color:best?P.solar:P.fb,fontFamily:fm,flexShrink:0}}>#{i+1}</div>
              <div style={{flex:1,minWidth:0}}><div style={{fontSize:11,fontWeight:700,color:P.txt,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{c.campaignName}</div><div style={{display:"flex",gap:6,marginTop:3}}><Pill name={c.accountName} color={P.orchid}/>{best&&<span style={{background:gFire,color:"#fff",fontSize:8,fontWeight:900,padding:"2px 8px",borderRadius:6,fontFamily:fm}}>BEST</span>}</div></div>
              <div style={{textAlign:"right",minWidth:60}}><div style={{fontSize:14,fontWeight:900,color:P.txt,fontFamily:fm}}>{fmt(parseFloat(c.clicks||0))}</div><div style={{fontSize:8,color:P.dim,fontFamily:fm}}>clicks</div></div>
              <div style={{textAlign:"right",minWidth:55}}><div style={{fontSize:13,fontWeight:800,color:P.mint,fontFamily:fm}}>{fR(parseFloat(c.cpc||0))}</div><div style={{fontSize:8,color:P.dim,fontFamily:fm}}>CPC</div></div>
              <div style={{textAlign:"right",minWidth:50}}><div style={{fontSize:13,fontWeight:700,color:P.sub,fontFamily:fm}}>{pc(parseFloat(c.ctr||0))}</div><div style={{fontSize:8,color:P.dim,fontFamily:fm}}>CTR</div></div>
              <div style={{textAlign:"right",minWidth:60}}><div style={{fontSize:13,fontWeight:700,color:P.ember,fontFamily:fm}}>{fR(parseFloat(c.spend||0))}</div><div style={{fontSize:8,color:P.dim,fontFamily:fm}}>spend</div></div>
            </div>;})}
            <Insight title="Engagement Analysis" accent={P.mint} icon={Ic.fire(P.mint,16)}>Meta has generated <strong>{fmt(m.clicks)} clicks</strong> at <strong>{fR(m.cpc)} CPC</strong> with {pc(m.ctr)} CTR — each click represents a deliberate intent signal from a user who has moved beyond passive awareness into active consideration. The CPC level indicates the campaign is winning competitive auctions efficiently, securing high-quality placements without overpaying for attention. TikTok contributed {fmt(t.clicks)} clicks alongside {fmt(t.follows)} new followers and {fmt(t.likes)} engagements — on TikTok, engagement metrics carry amplification weight as the algorithm promotes content with strong interaction signals. The combined click volume of <strong>{fmt(computed.totalClicks)}</strong> across both platforms confirms the creative messaging is resonating at scale, with each platform contributing its unique engagement character: Meta for measured, intentional interaction and TikTok for volume-driven social proof.</Insight>
          </Glass>
        </div>)}

        {/* OBJECTIVES */}
        {tab==="bof"&&(<div>
          <SH icon={Ic.target(P.rose,20)} title="Bottom of Funnel — Objective Results" sub="Results · Cost Per Result · Community Growth" accent={P.rose}/>

          <PH platform="Facebook" suffix="Objective Results"/>
          <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:14,marginBottom:24}}>
            {[{l:"IMPRESSIONS",v:fmt(m.impressions),s1l:"CPM",s1v:fR(m.cpm),s1c:P.fb,s2l:"SPEND",s2v:fR(m.spend)},{l:"CLICKS",v:fmt(m.clicks),s1l:"CPC",s1v:fR(m.cpc),s1c:P.fb,s2l:"CTR",s2v:pc(m.ctr)},{l:"REACH",v:fmt(m.reach),s1l:"FREQUENCY",s1v:m.frequency>0?m.frequency.toFixed(2)+"x":"N/A",s1c:P.fb}].map(function(x,i){return<Glass key={i} accent={P.fb} hv={true} st={{padding:20}}><div style={{fontSize:9,fontWeight:700,color:P.sub,fontFamily:fm,letterSpacing:2,marginBottom:12}}>{x.l}</div><div style={{fontSize:26,fontWeight:900,color:P.txt,fontFamily:fm}}>{x.v}</div><div style={{display:"flex",justifyContent:"space-between",paddingTop:10,borderTop:"1px solid "+P.rule,marginTop:10}}><div><div style={{fontSize:8,color:P.dim,fontFamily:fm}}>{x.s1l}</div><div style={{fontSize:15,fontWeight:800,color:x.s1c,fontFamily:fm}}>{x.s1v}</div></div>{x.s2l&&<div style={{textAlign:"right"}}><div style={{fontSize:8,color:P.dim,fontFamily:fm}}>{x.s2l}</div><div style={{fontSize:13,fontWeight:700,color:P.sub,fontFamily:fm}}>{x.s2v}</div></div>}</div></Glass>;})}
          </div>

          <PH platform="TikTok" suffix="Objective Results"/>
          <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:14,marginBottom:24}}>
            {[{l:"IMPRESSIONS",v:fmt(t.impressions),s1l:"CPM",s1v:fR(t.cpm),s1c:P.tt,s2l:"SPEND",s2v:fR(t.spend)},{l:"CLICKS",v:fmt(t.clicks),s1l:"CPC",s1v:t.clicks>0?fR(t.spend/t.clicks):"N/A",s1c:P.tt},{l:"COMMUNITY",v:fmt(t.follows),s1l:"LIKES",s1v:fmt(t.likes),s1c:P.tt}].map(function(x,i){return<Glass key={i} accent={P.tt} hv={true} st={{padding:20}}><div style={{fontSize:9,fontWeight:700,color:P.sub,fontFamily:fm,letterSpacing:2,marginBottom:12}}>{x.l}</div><div style={{fontSize:26,fontWeight:900,color:i===2?P.mint:P.txt,fontFamily:fm}}>{x.v}</div><div style={{paddingTop:10,borderTop:"1px solid "+P.rule,marginTop:10}}><div style={{fontSize:8,color:P.dim,fontFamily:fm}}>{x.s1l}</div><div style={{fontSize:15,fontWeight:800,color:x.s1c,fontFamily:fm}}>{x.s1v}</div></div>{x.s2l&&<div style={{marginTop:8}}><div style={{fontSize:8,color:P.dim,fontFamily:fm}}>{x.s2l}</div><div style={{fontSize:13,fontWeight:700,color:P.sub,fontFamily:fm}}>{x.s2v}</div></div>}</Glass>;})}
          </div>

          <Glass accent={P.ember} st={{padding:26,background:"linear-gradient(135deg,"+P.lava+"05,"+P.ember+"05,"+P.solar+"05)"}}>
            <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:22}}>{Ic.users(P.ember,18)}<span style={{fontSize:10,fontWeight:800,color:P.ember,letterSpacing:3,fontFamily:fm,textTransform:"uppercase"}}>Combined Results</span></div>
            <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:18}}>
              <div><div style={{fontSize:9,color:P.dim,fontFamily:fm,letterSpacing:2,marginBottom:6}}>IMPRESSIONS</div><div style={{fontSize:30,fontWeight:900,fontFamily:ff,lineHeight:1,color:P.ember}}>{fmt(computed.totalImps)}</div></div>
              <div style={{borderLeft:"1px solid "+P.rule,paddingLeft:16}}><div style={{fontSize:9,color:P.dim,fontFamily:fm,letterSpacing:2,marginBottom:6}}>SPEND</div><div style={{fontSize:22,fontWeight:900,color:P.solar,fontFamily:fm}}>{fR(computed.totalSpend)}</div></div>
              <div style={{borderLeft:"1px solid "+P.rule,paddingLeft:16}}><div style={{fontSize:9,color:P.dim,fontFamily:fm,letterSpacing:2,marginBottom:6}}>CLICKS</div><div style={{fontSize:22,fontWeight:900,color:P.mint,fontFamily:fm}}>{fmt(computed.totalClicks)}</div></div>
              <div style={{borderLeft:"1px solid "+P.rule,paddingLeft:16}}><div style={{fontSize:9,color:P.dim,fontFamily:fm,letterSpacing:2,marginBottom:6}}>TT FOLLOWS</div><div style={{fontSize:22,fontWeight:900,color:P.tt,fontFamily:fm}}>{fmt(t.follows)}</div></div>
            </div>
            <Insight title="Combined Campaign Read" icon={Ic.crown(P.ember,16)} accent={P.ember}>The selected campaigns have delivered <strong>{fmt(computed.totalImps)} total impressions</strong> across Meta and TikTok against a combined investment of <strong>{fR(computed.totalSpend)}</strong>, achieving a blended CPM of {fR(computed.blendedCpm)} — representing exceptional media value in the South African paid social market. Meta reached <strong>{fmt(m.reach)} unique individuals</strong> at {m.frequency>0?m.frequency.toFixed(2)+"x":"N/A"} frequency, generating {fmt(m.clicks)} clicks at {fR(m.cpc)} CPC with {pc(m.ctr)} CTR. TikTok delivered {fmt(t.impressions)} impressions at {fR(t.cpm)} CPM with {fmt(t.follows)} followers earned — building an owned audience asset that compounds in value with every campaign cycle. The dual-platform architecture is delivering its intended strategic outcome: TikTok provides the mass awareness foundation and cost-efficient community growth, whilst Meta converts that awareness into measurable, attributable engagement actions. This complementary approach ensures neither platform’s limitations constrain overall campaign performance — each amplifies the other’s strengths.</Insight>
          </Glass>
        </div>)}

        {/* OPTIMISATION */}
        {tab==="deepdive"&&(<div>
          <SH icon={Ic.eye(P.cyan,20)} title="Deep Dive" sub="Demographics, Creative Performance & Placement Analysis" accent={P.cyan}/>
          <Glass accent={P.cyan} st={{padding:"36px 32px",marginBottom:24}}>
            <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:20,marginBottom:28}}>
              <div style={{padding:24,background:P.fb+"08",border:"1px solid "+P.fb+"20",borderRadius:14,textAlign:"center"}}><div style={{fontSize:9,fontWeight:700,color:P.fb,letterSpacing:2,fontFamily:fm,marginBottom:8}}>DEMOGRAPHICS</div><div style={{fontSize:14,fontWeight:700,color:P.txt,marginBottom:4}}>Age, Gender, Location</div><div style={{fontSize:11,color:P.sub}}>Audience composition breakdown</div></div>
              <div style={{padding:24,background:P.tt+"08",border:"1px solid "+P.tt+"20",borderRadius:14,textAlign:"center"}}><div style={{fontSize:9,fontWeight:700,color:P.tt,letterSpacing:2,fontFamily:fm,marginBottom:8}}>CREATIVE</div><div style={{fontSize:14,fontWeight:700,color:P.txt,marginBottom:4}}>Ad Thumbnails & Performance</div><div style={{fontSize:11,color:P.sub}}>Visual creative ranking with metrics</div></div>
              <div style={{padding:24,background:P.orchid+"08",border:"1px solid "+P.orchid+"20",borderRadius:14,textAlign:"center"}}><div style={{fontSize:9,fontWeight:700,color:P.orchid,letterSpacing:2,fontFamily:fm,marginBottom:8}}>PLACEMENTS</div><div style={{fontSize:14,fontWeight:700,color:P.txt,marginBottom:4}}>Feed, Stories, Reels, Network</div><div style={{fontSize:11,color:P.sub}}>Delivery by placement type</div></div>
              <div style={{padding:24,background:P.mint+"08",border:"1px solid "+P.mint+"20",borderRadius:14,textAlign:"center"}}><div style={{fontSize:9,fontWeight:700,color:P.mint,letterSpacing:2,fontFamily:fm,marginBottom:8}}>OBJECTIVE RESULTS</div><div style={{fontSize:14,fontWeight:700,color:P.txt,marginBottom:4}}>Results by Campaign Objective</div><div style={{fontSize:11,color:P.sub}}>Objective-level performance data</div></div>
            </div>
            <div style={{textAlign:"center"}}><button onClick={function(){var r=findLookerUrl(campaigns,selected);if(r.url){window.open(r.url,"_blank");}else{alert("No Looker report configured for '"+r.client+"' yet.");}}} style={{background:gEmber,border:"none",borderRadius:14,padding:"16px 48px",color:"#fff",fontSize:15,fontWeight:800,fontFamily:ff,cursor:"pointer",boxShadow:"0 4px 24px "+P.ember+"40",display:"inline-flex",alignItems:"center",gap:10}}>Open Interactive Report {Ic.share("#fff",18)}</button><div style={{fontSize:11,color:P.dim,fontFamily:fm,marginTop:14}}>Opens Looker Studio in a new tab with full interactive drill-down analysis</div></div>
          </Glass>
          <Insight title="Deep Dive Analysis" accent={P.cyan} icon={Ic.eye(P.cyan,16)}>The Looker Studio report provides granular campaign analysis that complements the dashboard metrics above. It includes audience demographic breakdowns by age, gender, and geographic region, individual ad creative performance with visual thumbnails ranked by key metrics, placement-level delivery analysis across Feed, Stories, Reels, and Audience Network, and device-level performance data showing mobile versus desktop engagement patterns. Use the interactive filters within the report to drill into specific campaigns, date ranges, and audience segments.</Insight>
        </div>)}

        {tab==="optimise"&&!isClient&&(<div>
          <SH icon={Ic.flag(P.warning,20)} title="Optimisation — Flags & Recommendations" sub={flags.length+" flags · "+openFlags+" open · Auto-generated"} accent={P.warning}/>
          <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginBottom:24}}>
            {[{l:"CRITICAL",c:P.critical},{l:"WARNING",c:P.warning},{l:"INFO",c:P.info},{l:"POSITIVE",c:P.positive}].map(function(x){return<Glass key={x.l} accent={x.c} st={{padding:"18px 16px",textAlign:"center"}}><div style={{fontSize:9,fontWeight:700,color:x.c,letterSpacing:2,fontFamily:fm,marginBottom:6}}>{x.l}</div><div style={{fontSize:28,fontWeight:900,color:x.c,fontFamily:fm}}>{flags.filter(function(f){return f.severity===x.l.toLowerCase();}).length}</div></Glass>;})}
          </div>

          {flags.length===0&&<div style={{padding:40,textAlign:"center",color:P.dim,fontFamily:fm}}>No flags. Select campaigns and refresh.</div>}
          {flags.map(function(f){
            var c={critical:P.critical,warning:P.warning,info:P.info,positive:P.positive}[f.severity]||P.info;
            return<div key={f.id} style={{padding:"18px 22px",marginBottom:10,background:P.glass,border:"1px solid "+P.rule,borderLeft:"4px solid "+c,borderRadius:"0 12px 12px 0"}}>
              <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:10}}>
                <div style={{display:"flex",alignItems:"center",gap:10}}><SevBadge s={f.severity}/><Pill name={f.platform} color={f.platform==="TikTok"?P.tt:f.platform==="Cross-platform"?P.orchid:P.fb}/></div>
                <div style={{display:"flex",gap:6}}>
                  {f.status==="open"&&<button onClick={function(){ack(f.id);}} style={{background:P.glass,border:"1px solid "+P.rule,borderRadius:8,padding:"5px 12px",color:P.sub,fontSize:10,fontWeight:700,fontFamily:fm,cursor:"pointer"}}>Acknowledge</button>}
                  {(f.status==="open"||f.status==="acknowledged")&&<button onClick={function(){resolve(f.id);}} style={{background:P.mint+"15",border:"1px solid "+P.mint+"30",borderRadius:8,padding:"5px 12px",color:P.mint,fontSize:10,fontWeight:700,fontFamily:fm,cursor:"pointer"}}>Resolve</button>}
                  {f.status==="resolved"&&<span style={{fontSize:10,color:P.mint,fontFamily:fm,fontWeight:700}}>Resolved</span>}
                </div>
              </div>
              <div style={{fontSize:13,fontWeight:700,color:P.txt,marginBottom:6}}>{f.metric}: {f.currentValue} {f.severity!=="positive"?"exceeds":"beats"} {f.threshold} threshold</div>
              <div style={{fontSize:12,color:P.sub,lineHeight:1.8}}>{f.message}</div>
              <div style={{fontSize:12,color:c,marginTop:8}}><strong>Recommendation:</strong> {f.recommendation}</div>
            </div>;
          })}

          <Insight title="Optimisation Summary" accent={P.warning} icon={Ic.alert(P.warning,16)}>{flags.length} flags generated from selected campaign data. {openFlags} require attention. Review recommendations and take action to maintain optimal performance. Flags refresh when you change dates or campaign selection.</Insight>
        </div>)}

        </>)}
      </div>
    </div>

    <footer style={{borderTop:"1px solid "+P.rule,background:"rgba(6,2,14,0.95)",padding:"20px 28px"}}><div style={{maxWidth:1400,margin:"0 auto",display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{display:"flex",alignItems:"center",gap:10}}><div style={{width:26,height:26,borderRadius:"50%",background:gFire,display:"flex",alignItems:"center",justifyContent:"center",fontSize:7,fontWeight:900,color:"#fff",fontFamily:fm}}>GAS</div><span style={{fontSize:11,fontWeight:800,color:P.sub,fontFamily:fm,letterSpacing:2}}>MEDIA ON GAS</span><span style={{fontSize:9,color:P.dim}}>Powered by GAS Response Marketing</span></div><div style={{fontSize:9,color:P.dim,fontFamily:fm,textAlign:"right",lineHeight:1.8}}>Live data · All figures in ZAR · Confidential · grow@gasmarketing.co.za</div></div></footer>
  </div>);
}
